### ISSUE TITLE
validate client version cause fluentd start error

### ISSUE THREAD

**Issue by like-inspur** [uken/fluent-plugin-elasticsearch#531] opened 2019-01-21 09:34 UTC
I use fluent-plugin-elasticsearch 3.0.1 and elasticsearch 6.5.4. When I config output elasitcsearch with validate_client_version true, the fluentd start error and output error like this:
```log
log is DEPRECATED and will be removed in a future version. Use logs instead.
2019-01-21 09:33:04 +0000 [info]: fluent/log.rb:322:info: parsing config file is succeeded path="/etc/fluent/fluent.conf"
2019-01-21 09:33:04 +0000 [warn]: [es-metering] Could not connect Elasticsearch or obtain version. Assuming Elasticsearch 5.
2019-01-21 09:33:04 +0000 [error]: fluent/log.rb:362:error: config error file="/etc/fluent/fluent.conf" error_class=Fluent::ConfigError error="            Detected ES 5 but you use ES client 6.1.0.\n            Please consider to use 5.x series ES client.\n"
  2019-01-21 09:33:04 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.0.1/lib/fluent/plugin/out_elasticsearch.rb:251:in `configure'
  2019-01-21 09:33:04 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: /var/lib/gems/2.3.0/gems/fluentd-1.2.4/lib/fluent/plugin.rb:164:in `configure'
  2019-01-21 09:33:04 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: /var/lib/gems/2.3.0/gems/fluentd-1.2.4/lib/fluent/agent.rb:130:in `add_match'
  2019-01-21 09:33:04 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: /var/lib/gems/2.3.0/gems/fluentd-1.2.4/lib/fluent/agent.rb:72:in `block in configure'
  2019-01-21 09:33:04 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: /var/lib/gems/2.3.0/gems/fluentd-1.2.4/lib/fluent/agent.rb:64:in `each'
  2019-01-21 09:33:04 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: /var/lib/gems/2.3.0/gems/fluentd-1.2.4/lib/fluent/agent.rb:64:in `configure'
  2019-01-21 09:33:04 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: /var/lib/gems/2.3.0/gems/fluentd-1.2.4/lib/fluent/root_agent.rb:112:in `configure'
  2019-01-21 09:33:04 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: /var/lib/gems/2.3.0/gems/fluentd-1.2.4/lib/fluent/engine.rb:131:in `configure'
  2019-01-21 09:33:04 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: /var/lib/gems/2.3.0/gems/fluentd-1.2.4/lib/fluent/engine.rb:96:in `run_configure'
  2019-01-21 09:33:04 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: /var/lib/gems/2.3.0/gems/fluentd-1.2.4/lib/fluent/supervisor.rb:795:in `run_configure'
  2019-01-21 09:33:04 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: /var/lib/gems/2.3.0/gems/fluentd-1.2.4/lib/fluent/supervisor.rb:579:in `dry_run'
  2019-01-21 09:33:04 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: /var/lib/gems/2.3.0/gems/fluentd-1.2.4/lib/fluent/supervisor.rb:597:in `supervise'
  2019-01-21 09:33:04 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: /var/lib/gems/2.3.0/gems/fluentd-1.2.4/lib/fluent/supervisor.rb:502:in `run_supervisor'
  2019-01-21 09:33:04 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: /var/lib/gems/2.3.0/gems/fluentd-1.2.4/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
  2019-01-21 09:33:04 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2019-01-21 09:33:04 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2019-01-21 09:33:04 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: /var/lib/gems/2.3.0/gems/fluentd-1.2.4/bin/fluentd:8:in `<top (required)>'
  2019-01-21 09:33:04 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: /usr/local/bin/fluentd:22:in `load'
  2019-01-21 09:33:04 +0000 [debug]: fluent/supervisor.rb:502:run_supervisor: /usr/local/bin/fluentd:22:in `<main>'
```

**Comment by like-inspur** [comment] 2019-01-21 09:36
when I uncomment validate_client_version, it works well

**Comment by cosmo0920** [comment] 2019-01-21 09:38
Could you share your Fluentd configuration?

**Comment by cosmo0920** [comment] 2019-01-21 09:39
This causes because obtaining ES version failure at startup:

```
2019-01-21 09:33:04 +0000 [warn]: [es-metering] Could not connect Elasticsearch or obtain version. Assuming Elasticsearch 5.
```

**Comment by like-inspur** [comment] 2019-01-21 09:48
fluentd run in kubernetes pod and config is like this:
  system.conf: |-
    <system>
      root_dir /tmp/fluentd-buffers/
      workers 3
    </system>

  metering.conf: |-
    <source>
      @type kafka_group
      brokers kafka-0.kafka-svc:9093
      consumer_group metering
      topics metering
    </source>

    <match metering>
      @id es-metering
      @type elasticsearch
      @log_level info
      host elasticsearch
      port 9200
      logstash_format true
      validate_client_version true
      reconnect_on_error true
      logstash_prefix metering
      unrecoverable_error_types ["out_of_memory_error"]
      slow_flush_log_threshold 120.0
      flush_interval 30s
      request_timeout 15s
      <buffer>
        @type file
        path /fluentd/elasticsearch/metering
        total_limit_size 16G
        retry_type periodic
        retry_wait 30
        flush_mode interval
        flush_thread_count 10
        retry_forever true
        overflow_action block
      </buffer>
    </match>

**Comment by cosmo0920** [comment] 2019-01-21 10:48
Could you try https://github.com/uken/fluent-plugin-elasticsearch/pull/532 patch?
I guess that it is caused conatiner start up phase.
In this phase, Elasticsearch still yellow status and cannot communicate.
After several retries, ES plugin could communicate with Elasticsearch.

**Comment by cosmo0920** [comment] 2019-01-22 04:31
Thank you for confirming root cause of this issue.
I found that obtaining mechanism should be retryable.
I'll merge #532 when CIs are passed.

**Comment by cosmo0920** [comment] 2019-01-22 05:38
https://github.com/uken/fluent-plugin-elasticsearch/pull/532 is merged. Closing.

**Closed by cosmo0920** 2019-01-22 05:38 UTC
