### ISSUE TITLE
es fails to accept nested json with escaped characters "\"

### ISSUE THREAD

**Issue by nizarayari** [uken/fluent-plugin-elasticsearch#593] opened 2019-05-24 11:30 UTC
#### Problem
It seems that es will reject a json-in-json log whcih contains the escape character \ , for example:
```
{"log":"{\"appName\":\"adapter\",\"time\":\"2019-05-23T15:40:54.299\",\"message\":\"{\\\"level\\\":\\\"info\\\",\\\"message\\\":\\\"Awaiting Messages from queue...\\\"}\"}\n","stream":"stdout","time":"2019-05-23T15:40:54.2996761Z"}
```
...

#### Steps to replicate

Provide example config and message

my fluentd.conf is as follows:
```
<source>
      @id fluentd-containers.log
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/containers.log.pos
      tag raw.kubernetes.*
      read_from_head true
      <parse>
        @type multi_format
        <pattern>
          format json
          time_key time
          time_format %Y-%m-%dT%H:%M:%S.%NZ
        </pattern>
        <pattern>
          format /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
          time_format %Y-%m-%dT%H:%M:%S.%N%:z
        </pattern>
      </parse>
    </source>

    # Detect exceptions in the log output and forward them as one log entry.
    <match raw.kubernetes.**>
      @id raw.kubernetes
      @type detect_exceptions
      remove_tag_prefix raw
      message log
      stream stream
      multiline_flush_interval 5
      max_bytes 500000
      max_lines 1000
    </match>

    # Concatenate multi-line logs
    <filter **>
      @id filter_concat
      @type concat
      key message
      multiline_end_regexp /\n$/
      separator ""
    </filter>

    # Enriches records with Kubernetes metadata
    <filter kubernetes.**>
      @id filter_kubernetes_metadata
      @type kubernetes_metadata
    </filter>
```
#### Expected Behavior or What you need to ask
Send log field as a json to es
...

**Comment by cosmo0920** [comment] 2019-07-30 05:57
Some users use filter_parser to parse inner JSON in log:
https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/fluentd-elasticsearch/fluentd-es-configmap.yaml#L161-L177

Because kubernetes_metadata does not have parsing inner JSON functionality, we should use other plugin to parse inner JSON.

**Comment by cosmo0920** [comment] 2020-06-22 04:57
This issue should be stuck and not be shown ES plugin configuration.
This issue should not be reproducible issue. Closing.

**Closed by cosmo0920** 2020-06-22 04:57 UTC
Labels: waiting-on-feedback
