### ISSUE TITLE
Unable to Connect to ELS Pod using Openshift router

### ISSUE THREAD

**Issue by inkitm** [uken/fluent-plugin-elasticsearch#298] opened 2017-09-19 18:26 UTC
#### Problem
Hello

I am unable to push any data from the kafka plugin of fluentd to elastic search. We have tested the kafka plugin using stdout as output and it works fine. 
But when we switch to elastic search plugin and use the below config file, then we cannot see any records inserted in the elastic search.

```aconf
<match * >
    @type elasticsearch
    log_level info
    host "http://logging-es-logging.172.5.14.96.nip.io"
    index_name fluentd
    type_name fluentd
</match>
```

The host used here is the openshift route for the ELS pod and we are able to get the data into ELS using the same route address from curl command.

Please help !

**Comment by cosmo0920** [comment] 2017-09-20 03:14
Which versions of ES plugin and Fluentd?
Thanks.

**Comment by cosmo0920** [comment] 2017-09-20 03:30
And it would be appreciate if you could provide your stacktrace without sensitive information.

**Comment by cosmo0920** [comment] 2018-05-09 10:06
I create OpenShift Origin v3.9 environment in my local machine.

I guess that your configuration contains a mistake.
Could you try the following configuration?

```aconf
<match * >
    @type elasticsearch
    log_level info
    host "logging-es-logging.172.5.14.96.nip.io" # Without http scheme
    index_name fluentd
    type_name fluentd
    #scheme http
</match>
```

**Comment by cosmo0920** [comment] 2018-05-09 10:35
On my environment example result:

```log
% oc get all                                                                                                   (git)[release-3.9][OK]
NAME                              REVISION   DESIRED   CURRENT   TRIGGERED BY
deploymentconfigs/elasticsearch   1          1         1         config,image(elasticsearch:latest)

NAME                         DOCKER REPO                                   TAGS      UPDATED
imagestreams/elasticsearch   172.30.1.1:5000/elasticsearch/elasticsearch   latest    20 minutes ago

NAME                   HOST/PORT                                      PATH      SERVICES        PORT       TERMINATION   WILDCARD
routes/elasticsearch   elasticsearch-elasticsearch.127.0.0.1.nip.io             elasticsearch   9200-tcp                 None

NAME                       READY     STATUS        RESTARTS   AGE
po/elasticsearch-1-cjldc   1/1       Running       0          20m
po/kibana-1-deploy         0/1       Terminating   0          5m
po/kibana-1-nkbdr          0/1       Terminating   5          5m

NAME                 DESIRED   CURRENT   READY     AGE
rc/elasticsearch-1   1         1         1         20m

NAME                TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)             AGE
svc/elasticsearch   ClusterIP   172.30.165.28   <none>        9200/TCP,9300/TCP   20m
```

Above log says that `routes/elasticsearch` exposed with `elasticsearch-elasticsearch.127.0.0.1.nip.io` on port 80 (but ommitted).

I've confirmed that the following configuration works for me:

```aconf
<match * >
    @type elasticsearch
    log_level info
    host "elasticsearch-elasticsearch.127.0.0.1.nip.io" # Without http scheme
    port 80 # Omitted from `oc get all` output but it is exposed on port 80.
    index_name fluentd
    type_name fluentd
    #scheme http
</match>
```

And curl can access with `elasticsearch-elasticsearch.127.0.0.1.nip.io` without specifying port in URL.

**Comment by cosmo0920** [comment] 2018-05-10 09:04
I'm closing this issue.
@inkitm Could you add comment if you cannot communicate ES after configuration changing?

**Closed by cosmo0920** 2018-05-10 09:04 UTC
Labels: waiting-on-feedback
