### ISSUE TITLE
Fluentd hangs if unable to connect to elasticsearch

### ISSUE THREAD

**Issue by mightwork** [uken/fluent-plugin-elasticsearch#596] opened 2019-06-03 16:05 UTC
#### Problem
Fluentd hangs if it's unable to connect to elasticsearch.
```
2019-05-22 14:55:28 +0000 [info]: starting fluentd-1.3.3 pid=6 ruby="2.3.3"
2019-05-22 14:55:28 +0000 [info]: spawn command to main:  cmdline=["/usr/bin/ruby2.3", "-Eascii-8bit:ascii-8bit", "/fluentd/vendor/bundle/ruby/2.3.0/bin/fluentd", "-c", "/fluentd/etc/fluent.conf", "-p", "/fluentd/plugins", "--gemfile", "/fluentd/Gemfile", "--under-supervisor"]
2019-05-22 14:55:29 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '3.5.1'
2019-05-22 14:55:29 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '2.1.6'
2019-05-22 14:55:29 +0000 [info]: gem 'fluent-plugin-prometheus' version '1.4.0'
2019-05-22 14:55:29 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.2.0'
2019-05-22 14:55:29 +0000 [info]: gem 'fluent-plugin-s3' version '1.1.10'
2019-05-22 14:55:29 +0000 [info]: gem 'fluent-plugin-systemd' version '1.0.2'
2019-05-22 14:55:29 +0000 [info]: gem 'fluentd' version '1.3.3'
2019-05-22 14:55:29 +0000 [info]: adding match in @RETRY_EULER_ES pattern="**" type="elasticsearch"
2019-05-22 14:55:29 +0000 [warn]: #0 'log_level' is deprecated parameter name. use '@log_level' instead.
2019-05-22 14:55:30 +0000 [info]: #0 [out_euler_es_retry] Detected ES 6.x: ES 7.x will only accept `_doc` in type_name.
2019-05-22 14:55:30 +0000 [info]: adding match in @RETRY_ES pattern="**" type="elasticsearch"
2019-05-22 14:55:30 +0000 [warn]: #0 'log_level' is deprecated parameter name. use '@log_level' instead.
2019-05-22 14:56:32 +0000 [warn]: #0 [out_es_retry] Could not communicate to Elasticsearch, resetting connection and trying again. request timed out
2019-05-22 14:57:07 +0000 [warn]: #0 [out_es_retry] Could not communicate to Elasticsearch, resetting connection and trying again. Couldn't connect to server
2019-05-22 14:57:15 +0000 [warn]: #0 [out_es_retry] Could not communicate to Elasticsearch, resetting connection and trying again. Couldn't connect to server
2019-05-22 14:58:31 +0000 [warn]: #0 [out_es_retry] Could not communicate to Elasticsearch, resetting connection and trying again. request timed out
2019-05-22 15:00:03 +0000 [warn]: #0 [out_es_retry] Could not communicate to Elasticsearch, resetting connection and trying again. request timed out

```
Fluentd stays in the state indefinitely until I restart it. Rest of the plugins/rules are not even initialized. 

#### Steps to replicate
Make elasticsearch cluster unavailable. 

#### Expected Behavior or What you need to ask
Fluentd should skip over to the next rule if unable to connect to elasticsearch to the current one. This way at least some of the rules for example archive to S3 will still work. Don't know if this the intended behavior from fluentd's side. 
...

#### Using Fluentd and ES plugin versions

* OS version
 Linux  4.4.0-1054-aws #63-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux
* Bare Metal or within Docker or Kubernetes or others?
 Kubernetes
* Fluentd v0.12 or v0.14/v1.0
  fluentd 1.3.3
* ES plugin 3.x.y/2.x.y or 1.x.y
  3.5.1
```
2019-06-03 15:44:33 +0000 [info]: starting fluentd-1.3.3 pid=7 ruby="2.3.3"
2019-06-03 15:44:33 +0000 [info]: spawn command to main:  cmdline=["/usr/bin/ruby2.3", "-Eascii-8bit:ascii-8bit", "/fluentd/vendor/bundle/ruby/2.3.0/bin/fluentd", "-c", "/fluentd/etc/fluent.conf", "-p", "/fluentd/plugins", "--gemfile", "/fluentd/Gemfile", "--under-supervisor"]
2019-06-03 15:44:33 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '3.5.1'
2019-06-03 15:44:33 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '2.1.6'
2019-06-03 15:44:33 +0000 [info]: gem 'fluent-plugin-out_rawtcp' version '0.0.1'
2019-06-03 15:44:33 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.2.0'
2019-06-03 15:44:33 +0000 [info]: gem 'fluent-plugin-s3' version '1.1.10'
2019-06-03 15:44:33 +0000 [info]: gem 'fluent-plugin-systemd' version '1.0.2'
2019-06-03 15:44:33 +0000 [info]: gem 'fluentd' version '1.3.3'
```
  * paste result of ``fluent-gem list``, ``td-agent-gem list`` or your Gemfile.lock
```
*** LOCAL GEMS ***

activesupport (5.2.3)
addressable (2.6.0)
aws-eventstream (1.0.3)
aws-partitions (1.161.0)
aws-sdk-core (3.51.0)
aws-sdk-kms (1.18.0)
aws-sdk-s3 (1.36.1)
aws-sdk-sqs (1.13.0)
aws-sigv4 (1.1.0)
bigdecimal (1.2.8)
bundler (1.16.2)
concurrent-ruby (1.1.5)
cool.io (1.5.4)
dig_rb (1.0.1)
domain_name (0.5.20180417)
elasticsearch (7.0.0)
elasticsearch-api (7.0.0)
elasticsearch-transport (7.0.0)
ethon (0.12.0)
excon (0.64.0)
faraday (0.15.4)
ffi (1.10.0)
fluent-config-regexp-type (1.0.0)
fluent-plugin-elasticsearch (3.5.1)
fluent-plugin-kubernetes_metadata_filter (2.1.6)
fluent-plugin-out_rawtcp (0.0.1)
fluent-plugin-rewrite-tag-filter (2.2.0)
fluent-plugin-s3 (1.1.10)
fluent-plugin-systemd (1.0.2)
fluentd (1.3.3)
http (0.9.8)
http-cookie (1.0.3)
http-form_data (1.0.3)
http_parser.rb (0.6.0)
i18n (1.6.0)
io-console (0.4.5)
jmespath (1.4.0)
json (1.8.3)
kubeclient (1.1.4)
lru_redux (1.1.0)
mime-types (3.2.2)
mime-types-data (3.2019.0331)
minitest (5.11.3)
msgpack (1.2.10)
multi_json (1.13.1)
multipart-post (2.1.1)
netrc (0.11.0)
oj (3.5.1)
psych (2.1.0)
public_suffix (3.0.3)
rdoc (4.2.1)
recursive-open-struct (1.0.0)
rest-client (2.0.2)
serverengine (2.1.1)
sigdump (0.2.4)
strptime (0.2.3)
systemd-journal (1.3.3)
thread_safe (0.3.6)
typhoeus (1.3.1)
tzinfo (1.2.5)
tzinfo-data (1.2019.1)
unf (0.1.4)
unf_ext (0.0.7.6)
yajl-ruby (1.4.1)
```
* ES version
 7.0.1

**Comment by cosmo0920** [comment] 2019-06-04 01:48
@mightwork Where is your Fluentd Pod configuration?
Or, please show your using Fluentd Pod repository and revision?

**Comment by leandropadua** [comment] 2019-07-24 00:00
I'm facing a similar issue, I have fluentd running as a dameonset on my kubernetes windows nodes sending logs to elasticsearch and splunk. 

```
<match k8s_windows>
  @type copy
  <store ignore_error> 
    @type splunk_hec
    ...
  </store>
  <store ignore_error> 
    @type elasticsearch
     ...
  </store>
</match>
```
On my integration tests, I have a scenario when Elasticsearch is down and splunk is up. In this case, `fluentd` hangs trying to reconnect to elastic and do not send data to splunk.

```
019-07-24 09:36:23 +1000 [warn]: #0 Could not communicate to Elasticsearch, resetting connection and trying again. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. - connect(2) for 10.84.73.119:9200 (Errno::ETIMEDOUT)
```

My expected behavior would be that fluentd would continue sending logs to splunk. Am I missing something here?

I'm using fluent-plugin-elasticsearch-3.5.1, fluentd-1.4.2 on Windows 2019 server

**Comment by cosmo0920** [comment] 2019-07-29 07:08
> My expected behavior would be that fluentd would continue sending logs to splunk. Am I missing something here?

On `#configure` phase, ES plugin should wait until ES instance communication is succeeded.
And ES plugin blocks to launch Fluentd by default.
Because Fluentd requests to set up configuration correctly on `#configure` phase.

After `#configure` phase, it runs very fast and send events heavily in some heavily using case.

In this scenario, we need to set up configuration correctly until `#configure` phase.
So, we provide default parameter is too conservative to use advanced users.

To remove too pessimistic behavior, you can use the following configuration:

```aconf
<match **>
  @type elasticsearch
  # Some advanced users know their using ES version. 
  # We can disable it.
  verify_es_version_at_startup false
  # If you know that your using ES major version is 7, you can set as 7 here.
  default_elasticsearch_version 7
  # Very stable ES cluster, you can reduce retry operation counts. (minmum is 1)
  max_retry_get_es_version 1
  # Very stable ES cluster, you can reduce retry operation counts. (minmum is 1)
  max_retry_putting_template 1
  # ... and some configuration
</match>
```

**Comment by leandropadua** [comment] 2019-07-31 23:47
Hi @cosmo0920 
That solved the issue.
fluentd now starts normally, fails to send data to ES as expected and the data is sent to Splunk.
Thanks a lot for your answer.

**Comment by cosmo0920** [comment] 2019-08-01 01:05
OK. Thanks for confirming this. Closing.

**Closed by cosmo0920** 2019-08-01 01:05 UTC
Labels: waiting-on-feedback

**Comment by Sameer0998** [comment] 2025-05-08 10:24
```
        verify_es_version_at_startup false
        default_elasticsearch_version 7
        max_retry_get_es_version 5
        fail_on_detecting_es_version_retry_exceed false
        max_retry_putting_template 5
        fail_on_putting_template_retry_exceed false
```

this setting worked for me and can work for others as well.
