### ISSUE TITLE
Error occurred undefined method `to_msgpack'

### ISSUE THREAD

**Issue by redbox2000** [uken/fluent-plugin-elasticsearch#146] opened 2016-01-14 10:01 UTC
Hi  I am facing problem to_msgpack.

- Elasticsearch server 2.1.1
- fluent-plugin-elasticsearch 
- fluent-plugin-elasticsearch 1.3.0
- td-agent 0.12.19

if I downgrade td-agent into 0.12.12 it is normally again.

td-agent error message is below.

```
2016-01-14 19:04:10 +0900 [warn]: emit transaction failed: error_class=NoMethodError error="undefined method `to_msgpack' for #<BigDecimal:7ff073619598,'0.1274990320 2056885E1',27(27)>" tag="tag1"

2016-01-14 19:04:10 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-1.3.0/lib/fluent/plugin/out_elasticsearch.rb:124:in `to_msgpack'
2016-01-14 19:04:10 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluent-plugin-elasticsearch-1.3.0/lib/fluent/plugin/out_elasticsearch.rb:124:in `format'
2016-01-14 19:04:10 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/mixin.rb:90:in `block in format_stream'
2016-01-14 19:04:10 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/event.rb:128:in `call'
2016-01-14 19:04:10 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/event.rb:128:in `block in each'
2016-01-14 19:04:10 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/event.rb:127:in `each'
2016-01-14 19:04:10 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/event.rb:127:in `each'
2016-01-14 19:04:10 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/mixin.rb:87:in `format_stream'
2016-01-14 19:04:10 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/output.rb:250:in `emit'
2016-01-14 19:04:10 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/output.rb:32:in `next'
2016-01-14 19:04:10 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/plugin/out_copy.rb:74:in `emit'
2016-01-14 19:04:10 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/event_router.rb:88:in `emit_stream'
2016-01-14 19:04:10 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/plugin/in_tail.rb:245:in `receive_lines'
2016-01-14 19:04:10 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/plugin/in_tail.rb:337:in `call'
2016-01-14 19:04:10 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/plugin/in_tail.rb:337:in `wrap_receive_lines'
2016-01-14 19:04:10 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/plugin/in_tail.rb:529:in `call'
2016-01-14 19:04:10 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/plugin/in_tail.rb:529:in `on_notify'
2016-01-14 19:04:10 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/plugin/in_tail.rb:362:in `on_notify'
2016-01-14 19:04:10 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/plugin/in_tail.rb:463:in `call'
2016-01-14 19:04:10 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/plugin/in_tail.rb:463:in `on_change'
2016-01-14 19:04:10 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.2/lib/cool.io/loop.rb:88:in `run_once'
2016-01-14 19:04:10 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/cool.io-1.4.2/lib/cool.io/loop.rb:88:in `run'
2016-01-14 19:04:10 +0900 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.19/lib/fluent/plugin/in_tail.rb:230:in `run'
```

**Comment by pitr** [comment] 2016-01-14 14:37
Not sure what changed in 0.12.12...0.12.19 that could cause this, perhaps @repeatedly might know.

What is the message that you are sending to fluentd?

**Comment by repeatedly** [comment] 2016-01-14 15:43
We didn't change msgpack and related staff.
See: https://docs.treasuredata.com/articles/td-agent-changelog#20151224-version-v230

msgpack-ruby can't serialize BigDecimal object so td-agent 2.2.1 also should raise same error.

**Comment by redbox2000** [comment] 2016-01-15 02:39
Hi pitr

We are sending JSON format data. this problem is occurred by yum update. So I tried install from old  RPM package . Now the problem has been solved.
But I don't know why problem occurred if I use latest fluentd. I will contact the @repeatedly.

**Comment by repeatedly** [comment] 2016-01-15 03:17
I found the cause. Oj uses BigDeciaml instead of Float.
td-agent 2.1.3 uses Oj as default json parser instead of Yajl.

```rb
irb(main):001:0> require 'oj'
=> true
irb(main):002:0> Oj.load('{"a":999999999999999999999999999999.99999}')
=> {"a"=>#<BigDecimal:7ffb79a1ff00,'0.9999999999 9999999999 9999999999 99999E30',45(45)>}
irb(main):003:0> require 'yajl'
=> true
irb(main):004:0> Yajl.load('{"a":999999999999999999999999999999.99999}')
=> {"a"=>1.0e+30}
```

Setting `json_parser yajl` in input plugin resolve this problem.

**Comment by repeatedly** [comment] 2016-01-15 03:18
We can close this issue.

**Comment by repeatedly** [comment] 2016-01-15 04:03
I wil fix this different behaviour in the next fluentd release.
https://github.com/fluent/fluentd/issues/773

**Comment by pitr** [comment] 2016-01-16 04:22
Thanks @repeatedly! As always you are on top things!

**Closed by pitr** 2016-01-16 04:22 UTC
