### ISSUE TITLE
Failed to Flush Buffer - Read Timeout Reached / Connect_Write

### ISSUE THREAD

**Issue by DandyDeveloper** [uken/fluent-plugin-elasticsearch#590] opened 2019-05-21 13:08 UTC
#### Problem
Fluentbit forwarded data being thrown into ElasticSearch is throwing the following errors: 

```
2019-05-21 08:57:09 +0000 [warn]: #0 [elasticsearch] failed to flush the buffer. retry_time=2 next_retry_seconds=2019-05-21 08:57:10 +0000 chunk="5896207ac8a9863d02e19a5b261af84f" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"elastic-elasticsearch-client\", :port=>9200, :scheme=>\"http\"}): connect_write timeout reached"
```
and
```
2019-05-21 09:28:47 +0000 [warn]: #0 [elasticsearch] failed to flush the buffer. retry_time=21 next_retry_seconds=2019-05-21 09:29:20 +0000 chunk="5896207ad3da03c0dfea6b098566e810" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"elastic-elasticsearch-client\", :port=>9200, :scheme=>\"http\"}): read timeout reached"
```
This is without changing the default buffer config offered in the chart. I've increased it 100x but it's just not improving. 

I've also tried increasing my es client amount but no improvements. Oddly, there are 0 new entries being made because of these errors. 
...

#### Steps to replicate
Run the default elastic-stack chart on helm against a larger cluster (10 nodes) with a large number of pods producing logs.

#### Expected Behavior or What you need to ask
Expecting logs to correctly go into Elasticsearch
...

#### Using Fluentd and ES plugin versions

* OS version
CoreOS
* Bare Metal or within Docker or Kubernetes or others?
Bare Metal
* Fluentd v0.12 or v0.14/v1.0
Whatever is shipping with the helm chart.
* ES plugin 3.x.y/2.x.y or 1.x.y
2.4.0
* ES version (optional)
* ES template(s) (optional)

More details can be found here: https://github.com/helm/charts/issues/14018

**Comment by cosmo0920** [comment] 2019-05-21 13:44
This issue seems to be related to https://github.com/uken/fluent-plugin-elasticsearch#stopped-to-send-events-on-k8s-why.

**Comment by cosmo0920** [comment] 2019-05-21 13:45
This issue is not fluent-plugin-elasticsearch but helm/charts' fluent-elasticsearch charts issue.

**Comment by DandyDeveloper** [comment] 2019-05-21 14:11
@cosmo0920 Can you tell me why you think it's related? 

Even if I restart everything, I'm still presented with this problem. It's less a problem with the retires and a problem with the failure to flush the buffer.

**Comment by cosmo0920** [comment] 2019-05-21 14:56
Because highly loaded k8s and other platform can easily fire reloading connection issue which is caused by 10000 requests. This issue will always occur when sending 10000 requests with bulk API.

**Comment by mightwork** [comment] 2019-05-22 15:09
I am also seeing issues with my setup. Elasticsearch node heap keeps on increasing and then dies. Was serving similar traffic perfectly before this.
```
2019-05-22 15:01:43 +0000 [warn]: #0 [kube_out_es] failed to flush the buffer. retry_time=4 next_retry_seconds=2019-05-22 15:06:11 +0000 chunk="589789475fffaec927d18749220ea2cf" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"elasticsearch\", :port=>9200, :scheme=>\"http\", :user=>\"elastic\", :password=>\"obfuscated\"}): request timed out"
  2019-05-22 15:01:43 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluent-plugin-elasticsearch-3.5.1/lib/fluent/plugin/out_elasticsearch.rb:758:in `rescue in send_bulk'
  2019-05-22 15:01:43 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluent-plugin-elasticsearch-3.5.1/lib/fluent/plugin/out_elasticsearch.rb:734:in `send_bulk'
  2019-05-22 15:01:43 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluent-plugin-elasticsearch-3.5.1/lib/fluent/plugin/out_elasticsearch.rb:628:in `block in write'
  2019-05-22 15:01:43 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluent-plugin-elasticsearch-3.5.1/lib/fluent/plugin/out_elasticsearch.rb:627:in `each'
  2019-05-22 15:01:43 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluent-plugin-elasticsearch-3.5.1/lib/fluent/plugin/out_elasticsearch.rb:627:in `write'
  2019-05-22 15:01:43 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.3.3/lib/fluent/plugin/output.rb:1123:in `try_flush'
  2019-05-22 15:01:43 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.3.3/lib/fluent/plugin/output.rb:1423:in `flush_thread_run'
  2019-05-22 15:01:43 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.3.3/lib/fluent/plugin/output.rb:452:in `block (2 levels) in start'
  2019-05-22 15:01:43 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/2.3.0/gems/fluentd-1.3.3/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```

Also, fluentd worker doesn't start if the output plugin is unable to connect to elasticsearch.
```
2019-05-22 14:55:28 +0000 [info]: starting fluentd-1.3.3 pid=6 ruby="2.3.3"
2019-05-22 14:55:28 +0000 [info]: spawn command to main:  cmdline=["/usr/bin/ruby2.3", "-Eascii-8bit:ascii-8bit", "/fluentd/vendor/bundle/ruby/2.3.0/bin/fluentd", "-c", "/fluentd/etc/fluent.conf", "-p", "/fluentd/plugins", "--gemfile", "/fluentd/Gemfile", "--under-supervisor"]
2019-05-22 14:55:29 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '3.5.1'
2019-05-22 14:55:29 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '2.1.6'
2019-05-22 14:55:29 +0000 [info]: gem 'fluent-plugin-prometheus' version '1.4.0'
2019-05-22 14:55:29 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.2.0'
2019-05-22 14:55:29 +0000 [info]: gem 'fluent-plugin-s3' version '1.1.10'
2019-05-22 14:55:29 +0000 [info]: gem 'fluent-plugin-systemd' version '1.0.2'
2019-05-22 14:55:29 +0000 [info]: gem 'fluentd' version '1.3.3'
2019-05-22 14:55:29 +0000 [info]: adding match in @RETRY_EULER_ES pattern="**" type="elasticsearch"
2019-05-22 14:55:29 +0000 [warn]: #0 'log_level' is deprecated parameter name. use '@log_level' instead.
2019-05-22 14:55:30 +0000 [info]: #0 [out_euler_es_retry] Detected ES 6.x: ES 7.x will only accept `_doc` in type_name.
2019-05-22 14:55:30 +0000 [info]: adding match in @RETRY_ES pattern="**" type="elasticsearch"
2019-05-22 14:55:30 +0000 [warn]: #0 'log_level' is deprecated parameter name. use '@log_level' instead.
2019-05-22 14:56:32 +0000 [warn]: #0 [out_es_retry] Could not communicate to Elasticsearch, resetting connection and trying again. request timed out
2019-05-22 14:57:07 +0000 [warn]: #0 [out_es_retry] Could not communicate to Elasticsearch, resetting connection and trying again. Couldn't connect to server
2019-05-22 14:57:15 +0000 [warn]: #0 [out_es_retry] Could not communicate to Elasticsearch, resetting connection and trying again. Couldn't connect to server
2019-05-22 14:58:31 +0000 [warn]: #0 [out_es_retry] Could not communicate to Elasticsearch, resetting connection and trying again. request timed out
2019-05-22 15:00:03 +0000 [warn]: #0 [out_es_retry] Could not communicate to Elasticsearch, resetting connection and trying again. request timed out
```
My pods are stuck at this until eventually connection is established. Is this normal behaviour? It's understandable if I am only pushing to elasticsearch but this stop my S3 upload for archival purpose as well.

**Comment by DandyDeveloper** [comment] 2019-05-23 11:27
@cosmo0920 Issue was actually due to a mismatch in indices definitions. Really weird problem, I can close this. 

@mightwork These are separate issues I think

**Comment by cosmo0920** [comment] 2019-05-23 12:16
Oh, thanks for clarification!
I'm closing this issue.

@mightwork Could you open a new issue?

**Closed by cosmo0920** 2019-05-23 12:16 UTC

**Comment by imriss** [comment] 2019-07-31 13:30
@cosmo0920 I am facing the same issue. could you please elaborate about the mismatch that you mentioned? Thanks

**Comment by dkalashnik** [comment] 2019-10-01 08:07
Hi, I am facing the same issue, but for me, it is not a mismatch.
WIthout configured file buffer issue disappears.

My output config: 
```
<label @elasticsearch_output>
  <match **>
    @id elasticsearch
    @type elasticsearch
    @log_level info
    include_tag_key true
    tag_key logger
    type_name _doc
    host "#{ENV['OUTPUT_HOST']}"
    port "#{ENV['OUTPUT_PORT']}"
    scheme "#{ENV['OUTPUT_SCHEME']}"
    ssl_version "#{ENV['OUTPUT_SSL_VERSION']}"
    ssl_verify true
    logstash_format true
    logstash_prefix "#{ENV['LOGSTASH_PREFIX']}"
    logstash_dateformat %Y.%m.%d
    reload_connections false
    reconnect_on_error true
    reload_on_failure true
    request_timeout 15s
    <buffer>
      @type file
      path /var/log/fluentd-buffers/kubernetes.system.buffer
      flush_mode interval
      retry_type exponential_backoff
      flush_thread_count 4
      flush_interval 5s
      retry_forever
      retry_max_interval 30
      chunk_limit_size "2M"
      queue_limit_length "8"
      overflow_action block
    </buffer>
  </match>
</label>
```
Error:
```
2019-10-01 07:58:06 +0000 [warn]: [elasticsearch] failed to flush the buffer. retry_time=0 
next_retry_seconds=2019-10-01 07:58:07 +0000 chunk="593d4b40932b1de029ae3ce59f8560a9" 
error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure 
error="could not push logs to Elasticsearch cluster 
({:host=>\"elasticsearch-master\", :port=>9200, :scheme=>\"http\"}): 
read timeout reached"
  2019-10-01 07:58:06 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.4.3/lib/fluent/plugin/out_elasticsearch.rb:734:in `rescue in send_bulk'
  2019-10-01 07:58:06 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.4.3/lib/fluent/plugin/out_elasticsearch.rb:710:in `send_bulk'
  2019-10-01 07:58:06 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.4.3/lib/fluent/plugin/out_elasticsearch.rb:616:in `block in write'
  2019-10-01 07:58:06 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.4.3/lib/fluent/plugin/out_elasticsearch.rb:615:in `each'
  2019-10-01 07:58:06 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluent-plugin-elasticsearch-3.4.3/lib/fluent/plugin/out_elasticsearch.rb:615:in `write'
  2019-10-01 07:58:06 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.4.2/lib/fluent/plugin/output.rb:1125:in `try_flush'
  2019-10-01 07:58:06 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.4.2/lib/fluent/plugin/output.rb:1425:in `flush_thread_run'
  2019-10-01 07:58:06 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.4.2/lib/fluent/plugin/output.rb:454:in `block (2 levels) in start'
  2019-10-01 07:58:06 +0000 [warn]: /var/lib/gems/2.3.0/gems/fluentd-1.4.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
```


Any suggestions why it is not working with a buffer? 
I've tried different values for `chunk_limit_size`, `queue_limit_length`, `flush_interval` and `flush_thread_count`

Elasticsearch log doesn't contain any errors

**Comment by DandyDeveloper** [comment] 2019-10-02 00:44
Everyone, just an update on this. I discovered that whilst these buffer settings help. The underlining problem is ES is indeed rejecting or not getting to your task in time. 

Two things can be done to resolve this:

1. (Most important) figure out why your overloading your ES cluster. Typically this can be fixed by increasing your queue sizes on your nodes but be careful, as this is entirely dependent on how much  your nodes are capable of managing.
2. Increase the buffer timeout, it can be outrageous, but remember this also has downsides. 
```
<match *.**>
  ...
  request_timeout 2147483648
</match>
```

**Comment by dkalashnik** [comment] 2019-10-02 06:19
Finally, I was able to avoid that error. Large values for `flush_thread_count` leads to more frequent rate for that error.
With 4 I have a lot of them, with 2 fewer errors, with 1 no errors at all. I am not sure that elasticsearch is overloaded, without buffer it is working like a charm.

**Comment by ThaSami** [comment] 2021-01-17 14:55
for our case here it was a problem with ElasticSearch one of the pods restarted and never passed the readiness probs...
