### ISSUE TITLE
Using ${tag} into index_name or logstash_prefix does not expand

### ISSUE THREAD

**Issue by hjdr4** [uken/fluent-plugin-elasticsearch#94] opened 2015-03-20 14:31 UTC
This creates ${tag}-<date> ES indexes, instead of dynamic ones

**Comment by dterror** [comment] 2015-04-13 21:00
can you expand on that @hjdr4. I'm not sure I understood.

**Comment by jimmidyson** [comment] 2015-04-20 08:54
If I understand correctly this is the same as i put in a PR for at #91: dynamic index names based on tag contents.

**Comment by hjdr4** [comment] 2015-04-22 12:39
Yes that's what I mean,

For now, I have forked jimmidyson fork to have something like :
#now you can use ${tag} and ${whatever} or ${tag_prefix[i]}
  def interpolate(tag, str)
    #tag_parts = tag.split('.')
    #str.gsub(/\$\{tag_parts\[(\d+)\]\}/) { |m| tag_parts[$1.to_i] }
    if str=~ /\{tag_prefix/
	tag_parts = tag.split('.')
	str.gsub(/\$\{tag_prefix\[(\d+)\]\}/) { |m| tag_parts[$1.to_i..tag_parts.count-$1.to_i].join(".") }    
    else
    	eval(str.gsub(/\$\{(\w+)\}.*/) {|m| $1 })
    end
  end

The general idea is the ability to use "standard" variables as tag (we use $tag and $tag_prefix[i] currently)

**Comment by pitr** [comment] 2015-04-29 15:11
Closing as duplicate of #91

**Closed by pitr** 2015-04-29 15:11 UTC
