### ISSUE TITLE
memory not released

### ISSUE THREAD

**Issue by jeesim2** [uken/fluent-plugin-elasticsearch#128] opened 2015-09-07 07:29 UTC
hi.

when elasticsearch out_plugin receive large(1~5M) amount of data in a second 
it seems can't release memory.

#### configuration
```
<ROOT>
  <source>
    type monitor_agent
    bind 0.0.0.0
    port 24220
  </source>
  <source>
    type forward
    port 24224
  </source>
  <source>
    type tail
    path /home1/apps/fluentd/test_in_tail.log
    pos_file /home1/apps/fluentd/pos_in_tail.log
    refresh_interval 5
    tag test_in_tail
    format json
    log_level trace
  </source>
  <match *>
    type elasticsearch
    buffer_type file
    buffer_path /home1/apps/fluentd/buffer/*.buffer
    buffer_chunk_limit 32m
    buffer_queue_limit 1024
    logstash_format true
    utc_index true
    flush_interval 3
    disable_retry_limit true
    retry_waits 5s
    request_timeout 10
    num_threads 1
    host 110.199.16.147
    port 9200
    type_name dodol.analytics.dev
  </match>
</ROOT>
```
##### there is 150k line json file
* same same json list
```
[@dev]$ wc -l x_timestamp_wellformatted.log 
150000 x_timestamp_wellformatted.log
[@dev]$ head -n 1 x_timestamp_wellformatted.log 
{"@timestamp":"2015-09-07T12:04:28+09:00","mydatatest":"well formated"}
```

##### append json file to a file which in_tail plugin tracking.
* first 10k docs
* second 10k docs
* third 50k docs
```
[@dev]$ tail -n 10000 x_timestamp_wellformatted.log >> ~/apps/fluentd/test_in_tail.log  && date
2015. 09. 07. (월) 16:01:55 KST
[@dev]$ tail -n 10000 x_timestamp_wellformatted.log >> ~/apps/fluentd/test_in_tail.log  && date
2015. 09. 07. (월) 16:03:52 KST
[@dev]$ tail -n 50000 x_timestamp_wellformatted.log >> ~/apps/fluentd/test_in_tail.log  && date  
2015. 09. 07. (월) 16:04:33 KST

# 50k json's file size
[@dev]$ tail -n 50000 x_timestamp_wellformatted.log > 50k.log ^C
[@dev]$ ll -h | grep 50k.log
-rw-rw-r-- 1 irteam irteam 3.5M 2015-09-07 16:35 50k.log
```

##### this is elasticsearch's document count monitoring.
* indexed well accurately in a few seconds
```
[@dev-fluentd-realtime.ncl logs]$ for i in {1..10000} ; do curl localhost:9200/_cat/count; sleep 3; done
1441609298 16:01:38 602585 
1441609301 16:01:41 602585 
1441609304 16:01:44 602585 
1441609308 16:01:48 602585 
1441609311 16:01:51 602585 
1441609314 16:01:54 602585 
1441609317 16:01:57 602585 
1441609320 16:02:00 602585 
1441609323 16:02:03 612585  <--- 10k docs indexed
1441609326 16:02:06 612585 
1441609329 16:02:09 612585 
1441609332 16:02:12 612585 
1441609335 16:02:15 612585 
1441609338 16:02:18 612585 
1441609341 16:02:21 612585 
1441609344 16:02:24 612585 
1441609347 16:02:27 612585 
1441609350 16:02:30 612585 
1441609353 16:02:33 612585 
1441609356 16:02:36 612585 
1441609359 16:02:39 612585 
1441609362 16:02:42 612585 
1441609365 16:02:45 612585 
1441609368 16:02:48 612585 
1441609371 16:02:51 612585 
1441609374 16:02:54 612585 
1441609377 16:02:57 612585 
1441609380 16:03:00 612585 
1441609383 16:03:03 612585 
1441609386 16:03:06 612585 
1441609389 16:03:09 612585 
1441609392 16:03:12 612585 
1441609395 16:03:15 612585 
1441609398 16:03:18 612585 
1441609401 16:03:21 612585 
1441609404 16:03:24 612585 
1441609407 16:03:27 612585 
1441609410 16:03:30 612585 
1441609413 16:03:33 612585 
1441609416 16:03:36 612585 
1441609419 16:03:39 612585 
1441609422 16:03:42 612585 
1441609425 16:03:45 612585 
1441609428 16:03:48 612585 
1441609431 16:03:51 612585 
1441609434 16:03:54 612585 
1441609437 16:03:57 622585 <--- 10k docs indexed
1441609440 16:04:00 622585 
1441609443 16:04:03 622585 
1441609447 16:04:07 622585 
1441609450 16:04:10 622585 
1441609453 16:04:13 622585 
1441609456 16:04:16 622585 
1441609459 16:04:19 622585 
1441609462 16:04:22 622585 
1441609465 16:04:25 622585 
1441609468 16:04:28 622585 
1441609471 16:04:31 622585 
1441609474 16:04:34 622585 
1441609477 16:04:37 622585 
1441609480 16:04:40 622585 
1441609483 16:04:43 649377 
1441609486 16:04:46 672585  <--- 50k docs indexed
1441609489 16:04:49 672585 
1441609492 16:04:52 672585 
1441609495 16:04:55 672585 
1441609498 16:04:58 672585 
1441609501 16:05:01 672585 
1441609504 16:05:04 672585 
1441609507 16:05:07 672585 
1441609510 16:05:10 672585 
1441609513 16:05:13 672585 
1441609516 16:05:16 672585 
1441609519 16:05:19 672585 
1441609522 16:05:22 672585 
1441609525 16:05:25 672585 
1441609528 16:05:28 672585 
1441609531 16:05:31 672585
```

##### and this is the memory usage of fluentd process
```
[@dev-line-deco.ncl ~]$ for i in {1..1000000}; do ps -eo rss,cmd | grep fluentd | awk '{total += $1} END { print " memory_use_size_mb " total/1024}'; echo -n `date` ; sleep 3; done
 memory_use_size_mb 53.8125
2015. 09. 07. (월) 16:01:41 KST memory_use_size_mb 53.8203
2015. 09. 07. (월) 16:01:44 KST memory_use_size_mb 53.8242
2015. 09. 07. (월) 16:01:47 KST memory_use_size_mb 53.8242
2015. 09. 07. (월) 16:01:51 KST memory_use_size_mb 53.8281
2015. 09. 07. (월) 16:01:54 KST memory_use_size_mb 64.8672
2015. 09. 07. (월) 16:01:57 KST memory_use_size_mb 133.449 <--- when 10k docs indexed
2015. 09. 07. (월) 16:02:00 KST memory_use_size_mb 133.449
2015. 09. 07. (월) 16:02:04 KST memory_use_size_mb 133.449
2015. 09. 07. (월) 16:02:07 KST memory_use_size_mb 133.449
2015. 09. 07. (월) 16:02:10 KST memory_use_size_mb 133.449
2015. 09. 07. (월) 16:02:13 KST memory_use_size_mb 133.449
2015. 09. 07. (월) 16:02:17 KST memory_use_size_mb 133.449
2015. 09. 07. (월) 16:02:20 KST memory_use_size_mb 133.453
2015. 09. 07. (월) 16:02:23 KST memory_use_size_mb 133.449
2015. 09. 07. (월) 16:02:27 KST memory_use_size_mb 133.449
2015. 09. 07. (월) 16:02:30 KST memory_use_size_mb 133.449
2015. 09. 07. (월) 16:02:33 KST memory_use_size_mb 133.449
2015. 09. 07. (월) 16:02:36 KST memory_use_size_mb 133.449
2015. 09. 07. (월) 16:02:40 KST memory_use_size_mb 133.449
2015. 09. 07. (월) 16:02:43 KST memory_use_size_mb 133.449
2015. 09. 07. (월) 16:02:46 KST memory_use_size_mb 133.453
2015. 09. 07. (월) 16:02:50 KST memory_use_size_mb 133.449
2015. 09. 07. (월) 16:02:53 KST memory_use_size_mb 133.449
2015. 09. 07. (월) 16:02:56 KST memory_use_size_mb 133.449
2015. 09. 07. (월) 16:02:59 KST memory_use_size_mb 133.449
2015. 09. 07. (월) 16:03:03 KST memory_use_size_mb 133.449
2015. 09. 07. (월) 16:03:06 KST memory_use_size_mb 133.453
2015. 09. 07. (월) 16:03:09 KST memory_use_size_mb 133.449
2015. 09. 07. (월) 16:03:13 KST memory_use_size_mb 133.449
2015. 09. 07. (월) 16:03:16 KST memory_use_size_mb 133.453
2015. 09. 07. (월) 16:03:19 KST memory_use_size_mb 133.449
2015. 09. 07. (월) 16:03:22 KST memory_use_size_mb 133.449
2015. 09. 07. (월) 16:03:26 KST memory_use_size_mb 133.449
2015. 09. 07. (월) 16:03:29 KST memory_use_size_mb 133.449
2015. 09. 07. (월) 16:03:32 KST memory_use_size_mb 133.453
2015. 09. 07. (월) 16:03:35 KST memory_use_size_mb 133.449
2015. 09. 07. (월) 16:03:39 KST memory_use_size_mb 133.453
2015. 09. 07. (월) 16:03:42 KST memory_use_size_mb 133.449
2015. 09. 07. (월) 16:03:45 KST memory_use_size_mb 133.449
2015. 09. 07. (월) 16:03:49 KST memory_use_size_mb 133.449
2015. 09. 07. (월) 16:03:52 KST memory_use_size_mb 139.043 <--- when 10k docs indexed
2015. 09. 07. (월) 16:03:55 KST memory_use_size_mb 139.273
2015. 09. 07. (월) 16:03:58 KST memory_use_size_mb 139.273
2015. 09. 07. (월) 16:04:02 KST memory_use_size_mb 139.273
2015. 09. 07. (월) 16:04:05 KST memory_use_size_mb 139.273
2015. 09. 07. (월) 16:04:08 KST memory_use_size_mb 139.273
2015. 09. 07. (월) 16:04:12 KST memory_use_size_mb 139.273
2015. 09. 07. (월) 16:04:15 KST memory_use_size_mb 139.273
2015. 09. 07. (월) 16:04:18 KST memory_use_size_mb 139.277
2015. 09. 07. (월) 16:04:21 KST memory_use_size_mb 139.273
2015. 09. 07. (월) 16:04:25 KST memory_use_size_mb 139.273
2015. 09. 07. (월) 16:04:28 KST memory_use_size_mb 139.277
2015. 09. 07. (월) 16:04:31 KST memory_use_size_mb 167.184
2015. 09. 07. (월) 16:04:35 KST memory_use_size_mb 159.922
2015. 09. 07. (월) 16:04:38 KST memory_use_size_mb 302.41
2015. 09. 07. (월) 16:04:41 KST memory_use_size_mb 295.188  <--- when 50k docs indexed
2015. 09. 07. (월) 16:04:44 KST memory_use_size_mb 295.188
2015. 09. 07. (월) 16:04:48 KST memory_use_size_mb 295.188
2015. 09. 07. (월) 16:04:51 KST memory_use_size_mb 295.191
2015. 09. 07. (월) 16:04:54 KST memory_use_size_mb 295.191
2015. 09. 07. (월) 16:04:58 KST memory_use_size_mb 295.191
2015. 09. 07. (월) 16:05:01 KST memory_use_size_mb 295.211
2015. 09. 07. (월) 16:05:04 KST memory_use_size_mb 295.207
2015. 09. 07. (월) 16:05:07 KST memory_use_size_mb 295.207
2015. 09. 07. (월) 16:05:11 KST memory_use_size_mb 295.211
2015. 09. 07. (월) 16:05:14 KST memory_use_size_mb 295.207
2015. 09. 07. (월) 16:05:17 KST memory_use_size_mb 295.211
2015. 09. 07. (월) 16:05:21 KST memory_use_size_mb 295.207
2015. 09. 07. (월) 16:05:24 KST memory_use_size_mb 295.207
2015. 09. 07. (월) 16:05:27 KST memory_use_size_mb 295.207

25 minutes later.
2015. 09. 07. (월) 16:28:20 KST memory_use_size_mb 295.27
2015. 09. 07. (월) 16:28:23 KST memory_use_size_mb 295.27
2015. 09. 07. (월) 16:28:26 KST memory_use_size_mb 295.27 <--- still same usage

```

##### gem list
```
[dev-line-deco.ncl ~]$ gem list

*** LOCAL GEMS ***

bigdecimal (1.2.4)
cool.io (1.3.0)
elasticsearch (1.0.8)
elasticsearch-api (1.0.7)
elasticsearch-transport (1.0.7)
excon (0.45.3)
faraday (0.9.1)
fluent-mixin-config-placeholders (0.3.0)
fluent-plugin-better-timestamp (0.1.0)
fluent-plugin-elasticsearch (0.8.0, 0.7.0)
fluent-plugin-forest (0.3.0)
fluent-plugin-rewrite-tag-filter (1.5.1)
fluentd (0.12.7, 0.10.61)
http_parser.rb (0.6.0)
io-console (0.4.2)
json (1.8.1)
minitest (4.7.5)
msgpack (0.5.11)
multi_json (1.11.0)
multipart-post (2.0.0)
patron (0.4.20)
psych (2.0.5)
rake (10.1.0)
rdoc (4.1.0)
sigdump (0.2.2)
string-scrub (0.0.5, 0.0.3)
test-unit (2.1.3.0)
thread_safe (0.3.5)
tzinfo (1.2.2)
tzinfo-data (1.2015.2)
uuidtools (2.1.5)
yajl-ruby (1.2.1)
```

Even after all of new appended logs well indexed to elasticsearch in a seconds
fluentd process remain hold large RAM.

curios thing is when 2nd 10k documents indexed, RAM usage not raised so much.
but 50k documents indexted lastely it consumed 150 MB RAM more.

this is not reproducable with out_file plugin, but reproducable with elasticsearch plugin.
when this situation repeated all RAM of machines exhausted by fluentd.

##### If any one could tell me how can I dump heap of fluentd I will try it.
I've tried this article to dump & analyze heap but failed.
http://blog.skylight.io/hunting-for-leaks-in-ruby/

* added require
```
#!/usr/bin/env ruby
# -*- coding: utf-8 -*-
require 'rubygems' unless defined?(gem)
here = File.dirname(__FILE__)
$LOAD_PATH << File.expand_path(File.join(here, '..', 'lib'))
require 'fluent/command/fluentd'
require 'rbtrace'
```
* each of parent and child process not debuggable.
```
[dev]$  rbtrace -p 1803 -e 'Thread.new{require "objspace"; ObjectSpace.trace_object_allocations_start; GC.start(); ObjectSpace.dump_all(output: File.open("/home1/fluentd_heap.json", "w"))}.join'
*** run `sudo sysctl kernel.msgmnb=1048576` to prevent losing events (currently: 16384 bytes)
Error: argument --pid (pid is not listening for messages, did you `require "rbtrace"`).
Try --help for help.
```

**Comment by jeesim2** [comment] 2015-10-02 02:57
It is really easy to reproduce but I'm not a ruby guy so,, I am waiting someone.

**Comment by repeatedly** [comment] 2015-10-07 18:42
Which object is increased? Hash? Array?
Does elasticsearch-ruby have caches or similar mechanizm?

**Comment by jeesim2** [comment] 2015-10-07 21:17
@repeatedly I don't know which object increased.
I tried to profile objects in memory  but couldnt.

**Comment by dterror** [comment] 2015-10-08 20:55
I took a brief look at it last weekend and it seems like it was in the interaction with msg_pack. I totally removed elasticsearch-ruby and memory was still leaking.
I will update once I spend more time on it.

**Comment by repeatedly** [comment] 2015-10-13 07:02
@dterror Thanks for the investigation. I will also check msgpack and its memory handling.

**Comment by dterror** [comment] 2015-10-19 21:18
@jeesim2 Are you guys on Ruby 1.9?
I tried this on Ruby 2.2 and the leak was gone for me. Even with huge files, it stabilized at around 200M.

**Comment by jeesim2** [comment] 2015-10-20 00:14
I'm using ruby 2.1.2 or 2.1.3

$ ruby -version
ruby 2.1.3p242 (2014-09-19 revision 47630) [x86_64-linux]
-e:1:in `<main>': undefined local variable or method `rsion' for main:Object (NameError)

With how large file did you test?

1. (reproducable step > and this is the memory usage of fluentd process)
As you can see in my first write, ram usage not always getting high, but I think It raise when footprint is not capable with the new data.

2. btw, we can not expect 200mb to being released?

3. even today ruby consume 2GB of RAM.
(I am daily sending HUP(sig 1) to fluentd to restart child process by cron)

```
$ date
2015. 10. 20. ( 09:09:37 KST

$ top
top - 09:11:16 up 521 days, 12:58,  1 user,  load average: 0.00, 0.00, 0.00
Tasks: 138 total,   1 running, 137 sleeping,   0 stopped,   0 zombie
Cpu(s):  0.2%us,  0.2%sy,  0.0%ni, 99.7%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Mem:   3924372k total,  3608256k used,   316116k free,    82244k buffers
Swap:  2097144k total,   206156k used,  1890988k free,   823376k cached

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                                                                                                                                
 4589 irteam    20   0 3579m 2.4g 3856 S  0.7 65.1  92:12.71 ruby 

$ ps -eo pid,comm,lstart | grep ruby           
  705 ruby            Thu Jul 23 14:11:18 2015
 4589 ruby            Mon Oct 19 10:00:02 2015
```

**Comment by repeatedly** [comment] 2015-11-13 20:51
I tried several cases with 100000 nginx logs.
On my mac, memory usage is around 600MB by default es plugin.
Other cases.

- Change msgpack to json

No impact. Memory usage is same as msgpack.

- Call GC.start 

Memory usage is decreased but keep around 400MB.

- Change es plugin to td plugin

Memory usage is around 100MB.

I will check why es plugin consumes lots of memory.

**Comment by repeatedly** [comment] 2015-11-13 21:00
Ah wait, `Call GC.start at each flush` might be wrong. 
Need more time...

**Comment by repeatedly** [comment] 2015-11-13 22:49
I assume this is a GC slot problem.
`out_elasticsearch` plugin creates lots of objects in one `write` call but `out_file` and `out_tdlog` don't.
GC creates more slots, slot is used for Ruby's object, when existing slots are filled.
If in_tail reads lots of lines in shorter range, GC can't reuse existing slots so create more slots.
In streaming manner, this problem is not a critical.
In mixing batch and streaming manner with long-running, it becomes a problem.

> even today ruby consume 2GB of RAM.

But some users don't have this consumption problem so we need to investigate why this problem happens or not.

**Comment by jeesim2** [comment] 2015-11-18 23:32
I think this is not the only issue of es output plugin
 i am not sure, but there some more critical problem for me 
1. file buffer not flushed when large file tailed.
2. logs some times too many duplicated.
  x 10 times.
I have reported issues about these.

this plugin is good with less small traffic but not acceptable with relatively high traffic.
(I think it was not an hard traffic in my usecse )
I am sorry but looking for an alternative.

thanks for helps.:)

**Comment by repeatedly** [comment] 2015-11-24 09:09
> even today ruby consume 2GB of RAM.

Do other users hit this increasing problem?
I can't reproduce this on my environment...

**Comment by jeesim2** [comment] 2015-11-24 09:20
@repeatedly  that's very wired.
all of my production servers which vary purposed set up, encounter same issue.
is there any more information about my servers you need?

as I mentioned reproducing step is very simple.
whenever elasticsearch output used it make problem for both file input or tcp input.

**Comment by repeatedly** [comment] 2015-11-24 09:32
@jeesim2 I have already put my investigation is above. Memory is consumed but it stopped around x00MB.
I asked memory leak problems to my acquaintance's ES users on production but there is no issues. 
From this comment https://github.com/uken/fluent-plugin-elasticsearch/pull/112#issuecomment-135816052, this user also doesn't have issue with 2+ billion log records.

I'm not sure why this situation happens on your environment.
Did this happen with td-agent 2?

**Comment by pitr** [comment] 2016-04-25 05:17
closing old task

**Closed by pitr** 2016-04-25 05:17 UTC
Labels: level:Hard
