### ISSUE TITLE
Setting index_name breaks workchain

### ISSUE THREAD

**Issue by fleischer932** [uken/fluent-plugin-elasticsearch#346] opened 2018-01-10 13:20 UTC
#### Problem
Setting `index_name` doesn't work:
When I try to set the `index_name` in the match (`logstash_format` is set to `false`), Kibana cannot find the log entries.
However, the same config with `logstash_format true` works as expected.

#### Steps to replicate
Write a match-config with the following parts:
```
logstash_format true
logstash_prefix "mylogs"
type_name "Testtype"
```
In the upper case, the log entries are produced as expected.

Now change the config to use an own index. 

When using this config (rest exactly the same):
```
logstash_format false
index_name "testindex"
type_name "Testtype"
```
multiple other messages per second are created  (like: `2018/01/10 13:06:41 No metric client provided. Skipping metrics.` and several other ones, if required, please let me know) which are not produced by the service that is logged. 

The log entries from our service cannot be found, unlike before.

#### Expected Behavior or What you need to ask

The results visible in Kibana should be the same, except for the `_index`field.

#### Using Fluentd and ES plugin versions

OS version: I don't know, it runs on Minikube

Requested outputs:
```
fluentd --version
fluentd 0.12.33
```

```
td-agent --version
sh: td-agent: not found
```
* ES plugin 2.x.y or 1.x.y
  * paste boot log of fluentd or td-agent
  * paste result of ``fluent-gem list``, ``td-agent-gem list`` or your Gemfile.lock
```
fluent-gem list

*** LOCAL GEMS ***

activesupport (5.1.4)
addressable (2.5.2)
concurrent-ruby (1.0.5)
cool.io (1.4.6)
did_you_mean (1.0.0)
domain_name (0.5.20170404)
elasticsearch (5.0.4)
elasticsearch-api (5.0.4)
elasticsearch-transport (5.0.4)
excon (0.59.0)
faraday (0.13.1)
fluent-plugin-elasticsearch (1.10.0)
fluent-plugin-kubernetes_metadata_filter (0.29.0)
fluent-plugin-record-reformer (0.9.1)
fluent-plugin-secure-forward (0.4.5)
fluentd (0.12.33)
http (0.9.8)
http-cookie (1.0.3)
http-form_data (1.0.3)
http_parser.rb (0.6.0)
i18n (0.8.6)
json (2.0.3)
kubeclient (1.1.4)
lru_redux (1.1.0)
mime-types (3.1)
mime-types-data (3.2016.0521)
minitest (5.10.3)
msgpack (1.1.0)
multi_json (1.12.2)
multipart-post (2.0.0)
net-telnet (0.1.1)
netrc (0.11.0)
oj (2.18.5)
power_assert (0.2.6)
proxifier (1.0.3)
psych (2.1.0.1)
public_suffix (3.0.0)
recursive-open-struct (1.0.0)
resolve-hostname (0.1.0)
rest-client (2.0.2)
sigdump (0.2.4)
string-scrub (0.0.5)
test-unit (3.1.5)
thread_safe (0.3.6)
tzinfo (1.2.2)
tzinfo-data (1.2017.2)
unf (0.1.4)
unf_ext (0.0.7.4)
yajl-ruby (1.3.0)
```
```
td-agent-gem list
sh: td-agent-gem: not found
```

**Comment by cosmo0920** [comment] 2018-01-12 02:51
This is expected behavior.
If you use kibana and fluent-plugin-elasticsearch together, you should use `logstash_format true`by default due to default kibana index style.
This style requests incoming index_name as `<your index name>-YYYY.mm.dd`.
Then, index patterns should be `<your index name>-2017-12*`.

If you feel this is serious a pitfall for using EFK stack, could you consider to write documentation note and send PR?

**Comment by fleischer932** [comment] 2018-01-12 11:30
Thanks for the fast response.

The problem is, that I have a requirement to write to a fixed index every day (without date). 
Therefore: Is is possible to define the index to be just <your index name> instead of <your index name>-2017-12*? If that would be possible, it would solve my problem.

Is it possible by:
Using a date format that is "empty"? (I don't know how to define it)
Did I miss a flag that says: "Do not add date"? (I thought I read all of them multiple times)?
Other possibilities I can't think of now?

If this is not possible yet, I think it would be a great new feature ;)

**Comment by fleischer932** [comment] 2018-01-15 12:36
@cosmo0920 thanks for your reply. 
As mentioned in my last comment, it is an important requirement.
How and where can I write a `documentation note`, and what is `PR` and how can I send it to him/her/it?

**Comment by cosmo0920** [comment] 2018-01-16 09:36
IMO, fixed indices causes performance degradation.
I don't recommend to use fixed indices.



> How and where can I write a `documentation note`, and what is `PR` and how can I send it to him/her/it?

Please write your suggestion to fix documentation in README.md and then, send pull request it this repository.

**Comment by fleischer932** [comment] 2018-01-16 12:51
I hope I understood you correctly:
You ask me to update the documentation.
The problem is, that I do not have a suggestion to fix the documentation, since I do not know how to achieve what I want.

If you would state it is impossible to write to a specified index, I could fix the docu and send a pull-request. However, if there is a solution, I cannot fix the documentation, since I don't know it.

**Comment by cosmo0920** [comment] 2018-01-16 15:33
I hope you would post your question in elastic forum for feasibility.
Also I have no idea to achieve what you want.
If Elasticsearch + Kibana without fluent-plugin-elasticsearch cannot handle metrics for fixed indices,
this plugin does not archive your feature request.

**Comment by cosmo0920** [comment] 2018-03-06 09:43
This issue seems to be Kibana usage.
Please send your question which is "Why Kinaba does not handle fixed index without datetime and `@timestamp` field?" into [Kibana category in elasticsearch forum](https://discuss.elastic.co/c/kibana).
Thanks.

**Closed by cosmo0920** 2018-03-06 09:43 UTC
Labels: incomplete
