### ISSUE TITLE
ILM Applied - but getting rollover error does not match pattern

### ISSUE THREAD

**Issue by waynetaylor** [uken/fluent-plugin-elasticsearch#752] opened 2020-05-03 19:53 UTC
(check apply)
- [x] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

#### Problem
Indexes are not rolling over and provide the following error e.g:
```
illegal_argument_exception: index name [debug-2020.05.03] does not match pattern '^.*-\d+$'
```
...

#### Steps to replicate

Per documentation I have configured, ILM and made my own policy. For simplicity of testing I set this to roll over on either 1 day or 50kb or 100 documents. 

```
PUT _ilm/policy/fluentd-test-policy
{
  "policy": {
    "phases": {
      "hot": {
        "min_age": "0ms",
        "actions": {
          "rollover": {
            "max_age": "1d",
            "max_size": "50kb",
            "max_docs": 100
          },
          "set_priority": {
            "priority": 100
          }
        }
      },
      "delete": {
        "min_age": "7d",
        "actions": {
          "delete": {}
        }
      }
    }
  }
}
```

I then have applied a simple index template as follows:

```
PUT _template/debug
{
  "index_patterns": ["debug*"],
  "order": 1,
  "settings": {
    "number_of_shards": "1",
    "number_of_replicas": "0",
    "refresh_interval": "60s",
    "index.lifecycle.name": "fluentd-test-policy",
    "index.lifecycle.rollover_alias": "debug-logs"
  },
  "aliases" : {
        "debug-logs" : { }
      }
}
```

My Fluentd.conf file:
```
<match debug.**>  <store>
    @type elasticsearch
    scheme https
    log_es_400_reason true
    rollover_index true
    ssl_version TLSv1_2
    host <REMOVED>
    port <REMOVED>
    user <REMOVED
    password <REMOVED>
    enable_ilm true
    logstash_format true
    logstash_prefix debug
    index_date_pattern "now/d"
    ilm_policy_id fluentd-test-policy
    ilm_policy {"policy":{"phases":{"hot":{"min_age":"0ms","actions":{"rollover":{"max_age":"1d","max_size":"50kb","max_docs":100},"set_priority":{"priority":100}}},"delete":{"min_age":"7d","actions":{"delete":{}}}}}}
    template_name debug
    customize_template {}
    deflector_alias debug-logs
    id_key _hash
    remove_keys _hash
    <buffer tag, time>
      @type file
      path /var/log/fluentd/es-build
      timekey 60
      flush_mode interval
      flush_thread_count 4
      flush_interval 10s
      slow_flush_log_threshold 45.0
      chunk_full_threshold 0.9
      queue_limit_length 250m
      overflow_action drop_oldest_chunk
      # retry_forever
      retry_type exponential_backoff
      retry_timeout 10m
      retry_max_interval 60
    </buffer>
    reconnect_on_error true
    reload_on_failure true
    reload_connections false
    request_timeout 60s
  </store>
</match>
```

#### Expected Behavior or What you need to ask
Rollover index is created and ILM is transitioned as expected

#### Using Fluentd and ES plugin versions

* OS version: Ubuntu 18.04 Bionic
* EC2 Deployment
* Fluentd td-agent 1.10.2
* ES plugin 4.0.7
  * td-agent log

```
"/var/log/td-agent/td-agent.log" [readonly] 56095L, 5396648C                                                                                                                      53056,1       94%
  chunk_full_threshold 0.9
  queue_limit_length 250m
  overflow_action drop_oldest_chunk
  retry_type exponential_backoff
  retry_timeout 10m
  retry_max_interval 60
</buffer> is not used.
2020-05-03 19:42:10 +0000 [info]: #0 starting fluentd worker pid=9645 ppid=9639 worker=0
2020-05-03 19:42:10 +0000 [debug]: #0 restoring buffer file: path = /var/log/fluentd/es-build/buffer.b5a4c39b9ec67a28754a587f6b1e64e53.log
2020-05-03 19:42:10 +0000 [debug]: #0 buffer started instance=69853234533220 stage_size=16925 queue_size=0
2020-05-03 19:42:10 +0000 [debug]: #0 flush_thread actually running
2020-05-03 19:42:10 +0000 [debug]: #0 enqueue_thread actually running
2020-05-03 19:42:10 +0000 [debug]: #0 flush_thread actually running
2020-05-03 19:42:10 +0000 [debug]: #0 flush_thread actually running
2020-05-03 19:42:10 +0000 [info]: #0 [input_debug_agent] listening dRuby uri="druby://127.0.0.1:24230" object="Fluent::Engine" worker=0
2020-05-03 19:42:10 +0000 [info]: #0 [input_forward] listening port port=24224 bind="0.0.0.0"
2020-05-03 19:42:10 +0000 [info]: #0 fluentd worker is now running worker=0
2020-05-03 19:42:11 +0000 [debug]: #0 Created new chunk chunk_id="5a4c39c49f6849285edb1cc567b3dd04" metadata=#<struct Fluent::Plugin::Buffer::Metadata timekey=1588534920, tag="debug.test", variables=nil, seq=0>
2020-05-03 19:42:11 +0000 [debug]: #0 flush_thread actually running
2020-05-03 19:42:48 +0000 [debug]: #0 Created new chunk chunk_id="5a4c39e863d02a0b6b3b6a72b1efdb14" metadata=#<struct Fluent::Plugin::Buffer::Metadata timekey=1588534920, tag="debug.test", variables=nil, seq=0>
2020-05-03 19:42:58 +0000 [debug]: #0 Created new chunk chunk_id="5a4c39f1ff345c0e3b8ffee320616815" metadata=#<struct Fluent::Plugin::Buffer::Metadata timekey=1588534920, tag="debug.test", variables=nil, seq=0>
2020-05-03 19:43:00 +0000 [debug]: #0 Created new chunk chunk_id="5a4c39f3245bc04ae2756c3a19f8d1be" metadata=#<struct Fluent::Plugin::Buffer::Metadata timekey=1588534980, tag="debug.test", variables=nil, seq=0>
2020-05-03 19:43:10 +0000 [debug]: #0 Created new chunk chunk_id="5a4c39fd715033be53de54a639a41390" metadata=#<struct Fluent::Plugin::Buffer::Metadata timekey=1588534980, tag="debug.test", variables=nil, seq=0>
2020-05-03 19:43:20 +0000 [debug]: #0 Created new chunk chunk_id="5a4c3a06fc90a6dbf72cdbc28d676f3e" metadata=#<struct Fluent::Plugin::Buffer::Metadata timekey=1588534980, tag="debug.test", variables=nil, seq=0>
2020-05-03 19:43:30 +0000 [debug]: #0 Created new chunk chunk_id="5a4c3a1084a6e05402651a2b41454bf4" metadata=#<struct Fluent::Plugin::Buffer::Metadata timekey=1588534980, tag="debug.test", variables=nil, seq=0>
2020-05-03 19:43:40 +0000 [debug]: #0 Created new chunk chunk_id="5a4c3a1a0e8b866593829d5b5354aa75" metadata=#<struct Fluent::Plugin::Buffer::Metadata timekey=1588534980, tag="debug.test", variables=nil, seq=0>
2020-05-03 19:43:50 +0000 [debug]: #0 Created new chunk chunk_id="5a4c3a23990eb6726aa2bfdab46f8118" metadata=#<struct Fluent::Plugin::Buffer::Metadata timekey=1588534980, tag="debug.test", variables=nil, seq=0>
2020-05-03 19:44:00 +0000 [debug]: #0 Created new chunk chunk_id="5a4c3a2c5cf5edd35fdf15d9e0db026f" metadata=#<struct Fluent::Plugin::Buffer::Metadata timekey=1588535040, tag="debug.test", variables=nil, seq=0>
2020-05-03 19:44:10 +0000 [debug]: #0 Created new chunk chunk_id="5a4c3a36ad99ef16f0753cb9968dc758" metadata=#<struct Fluent::Plugin::Buffer::Metadata timekey=1588535040, tag="debug.test", variables=nil, seq=0>
2020-05-03 19:44:20 +0000 [debug]: #0 Created new chunk chunk_id="5a4c3a403787dafc7dd53187f7cfb7bd" metadata=#<struct Fluent::Plugin::Buffer::Metadata timekey=1588535040, tag="debug.test", variables=nil, seq=0>
2020-05-03 19:44:30 +0000 [debug]: #0 Created new chunk chunk_id="5a4c3a49bfa4bf3322b1e3aa8b77b60e" metadata=#<struct Fluent::Plugin::Buffer::Metadata timekey=1588535040, tag="debug.test", variables=nil, seq=0>
2020-05-03 19:44:40 +0000 [debug]: #0 Created new chunk chunk_id="5a4c3a5349cb2df0c233223bd4947091" metadata=#<struct Fluent::Plugin::Buffer::Metadata timekey=1588535040, tag="debug.test", variables=nil, seq=0>
2020-05-03 19:44:50 +0000 [debug]: #0 Created new chunk chunk_id="5a4c3a5cd3358494313c3c6ac76c707b" metadata=#<struct Fluent::Plugin::Buffer::Metadata timekey=1588535040, tag="debug.test", variables=nil, seq=0>
2020-05-03 19:45:00 +0000 [debug]: #0 Created new chunk chunk_id="5a4c3a65958ca98542c8ef652794485e" metadata=#<struct Fluent::Plugin::Buffer::Metadata timekey=1588535100, tag="debug.test", variables=nil, seq=0>
```
  * td-agent-gem list

```
*** LOCAL GEMS ***

addressable (2.7.0)
async (1.24.2)
async-http (0.50.8)
async-io (1.27.7)
async-pool (0.2.0)
aws-eventstream (1.1.0)
aws-partitions (1.297.0)
aws-sdk-core (3.94.0)
aws-sdk-kms (1.30.0)
aws-sdk-s3 (1.63.0)
aws-sdk-sqs (1.24.0)
aws-sigv4 (1.1.1)
bigdecimal (default: 1.3.2)
bundler (1.16.6)
concurrent-ruby (1.1.6)
console (1.8.2)
cool.io (1.6.0)
did_you_mean (1.1.0)
digest-crc (0.5.1)
elasticsearch (6.8.1)
elasticsearch-api (6.8.1)
elasticsearch-transport (6.8.1)
excon (0.73.0)
faraday (0.17.3)
ffi (1.12.2)
fluent-config-regexp-type (1.0.0)
fluent-logger (0.8.2)
fluent-plugin-elasticsearch (4.0.7)
fluent-plugin-kafka (0.13.0)
fluent-plugin-prometheus (1.7.3)
fluent-plugin-prometheus_pushgateway (0.0.2)
fluent-plugin-record-modifier (2.1.0)
fluent-plugin-rewrite-tag-filter (2.2.0)
fluent-plugin-s3 (1.3.1)
fluent-plugin-systemd (1.0.2)
fluent-plugin-td (1.1.0)
fluent-plugin-td-monitoring (0.2.4)
fluent-plugin-webhdfs (1.2.4)
fluentd (1.10.2)
hirb (0.7.3)
http_parser.rb (0.6.0)
httpclient (2.8.2.4)
io-console (default: 0.4.6)
ipaddress (0.8.3)
jmespath (1.4.0)
json (default: 2.0.4)
ltsv (0.1.2)
mini_portile2 (2.4.0)
minitest (5.10.1)
mixlib-cli (1.7.0)
mixlib-config (2.2.4)
mixlib-log (1.7.1)
mixlib-shellout (2.2.7)
msgpack (1.3.3)
multi_json (1.14.1)
multipart-post (2.1.1)
net-telnet (0.1.1)
nio4r (2.5.2)
nokogiri (1.10.9)
ohai (6.20.0)
oj (3.8.1)
openssl (default: 2.0.9)
parallel (1.19.1)
power_assert (0.4.1)
prometheus-client (0.9.0)
protocol-hpack (1.4.2)
protocol-http (0.15.1)
protocol-http1 (0.10.3)
protocol-http2 (0.11.6)
psych (default: 2.2.2)
public_suffix (4.0.4)
quantile (0.2.1)
rake (12.3.3, 12.0.0)
rdkafka (0.7.0)
rdoc (default: 5.0.1)
ruby-kafka (1.0.0)
ruby-progressbar (1.10.1)
rubyzip (1.3.0)
serverengine (2.2.1)
sigdump (0.2.4)
strptime (0.2.3)
systemd-journal (1.3.3)
systemu (2.5.2)
td (0.16.8)
td-client (1.0.7)
td-logger (0.3.27)
test-unit (3.2.3)
timers (4.3.0)
tzinfo (2.0.2)
tzinfo-data (1.2019.3)
webhdfs (0.9.0)
xmlrpc (0.2.1)
yajl-ruby (1.4.1)
zip-zip (0.3)
```

* ES version 7.6.2
<img width="856" alt="Screen Shot 2020-05-03 at 2 18 39 PM" src="https://user-images.githubusercontent.com/2912112/80924434-836ac700-8d4e-11ea-83d8-fa678597559b.png">

**Comment by cosmo0920** [comment] 2020-05-17 04:15
Cc: @kumaravel29 ?

**Comment by cosmo0920** [comment] 2020-05-18 01:25
This should be similar issue to be originated from https://github.com/uken/fluent-plugin-elasticsearch/blob/master/README.md#rollover_index ?
To create rollover_index, you should set up customize_template parameter with non-empty Hash parameter.

**Comment by waynetaylor** [comment] 2020-05-18 02:09
Even with this set I get error. 

Template config:
`PUT _template/debug
{
  "index_patterns": ["debug*"],
  "order": 1,
  "settings": {
    "number_of_shards": "1",
    "number_of_replicas": "0",
    "refresh_interval": "60s",
    "index.lifecycle.name": "fluentd-test-policy",
    "index.lifecycle.rollover_alias": "debug-logs"
  },
  "aliases" : {
        "debug-logs" : { }
      }
}`

customize_template value: `customize_template {"<<index_prefix>>": "debug"}`

**Comment by waynetaylor** [comment] 2020-05-18 02:10
<img width="842" alt="Screen Shot 2020-05-17 at 9 10 14 PM" src="https://user-images.githubusercontent.com/2912112/82167910-da11ee00-9882-11ea-9b5c-cab4b88f0ab7.png">

**Comment by kumaravel29** [comment] 2020-05-19 09:50
@waynetaylor the index name does not follow the rules of the rollover criteria.
Can you confirm if you have set the rollover_index to true?

**Comment by waynetaylor** [comment] 2020-05-20 12:52
@kumaravel29  - yes this is set to true.

**Comment by kumaravel29** [comment] 2020-05-20 13:09
@waynetaylor can you disable the logstash_format to false and test once

**Comment by waynetaylor** [comment] 2020-05-20 13:19
@kumaravel29  - when I add that I see nothing in elasticsearch for indexes. I put in debug mode and all I see is: 

2020-05-20 13:16:34 +0000 [debug]: #1 Created new chunk chunk_id="5a6143485690b7895b78b3e010843b3c" metadata=#<struct Fluent::Plugin::Buffer::Metadata timekey=1589980560, tag="debug.test", variables=nil, seq=0>

**Comment by waynetaylor** [comment] 2020-05-20 13:19
@kumaravel29  - could you provide a working example on your side. I will update mine to match and see if the same issue

**Comment by kumaravel29** [comment] 2020-05-20 16:06
@waynetaylor I tried testing and the rollover_index was not effective because template_file was missing. Can you test after adding a template file

**Comment by waynetaylor** [comment] 2020-05-20 17:42
@kumaravel29  on step further. I now have a rollover index. YAY ... I then got a different error (one of which I need to raise another bug). See below:

- If I delete template in elasticsearch. On startup, new data is indexed without properties of my index template JSON file. I later see a template created in elastic with correct settings so guessing this is an ordering issue in code maybe?

- If I leave my template as is (see above for initial ticket). I then get: illegal_argument_exception: Rollover alias [debug-logs] can point to multiple indices, found duplicated alias [[debug-logs]] in index template [debug].

- If I remove out the alias in template. Index is created with rollover - but no ILM policy details are associated. 

Wayne

**Comment by kumaravel29** [comment] 2020-05-20 19:36
@waynetaylor and @cosmo0920  there seems that the ilm, custom_template and rollover_index configuration are tightly coupled and impacting each other. Therefore the settings have to be very carefully used.
My answers for the 3 scenarios mentioned by @waynetaylor 
- I have tested and the index template is created before creating the rollover_index. So the ordering does not seem to be an issue but ILM configuration tends to overwrite values in the template and hence there is an chance the template might not have the correct index pattern.(This happened while I was testing)

- Ideally the alias used for rollover is not set in the alias section of the template and is directly set through fluent. Otherwise all the indices matching the pattern would get the alias and cause error.

- I have some trouble with ILM in my setup but the ILM policy is attached with the index creation.

**Comment by waynetaylor** [comment] 2020-05-22 22:25
Hi @cosmo0920  / @kumaravel29  - thanks for the write up. I am confused based upon the above next steps? Is this an issue OR is this an issue in my configuration? 

Could you provide a working example in the case of its user error?

**Comment by cosmo0920** [comment] 2020-05-28 03:16
Currently, ES plugin uses template to link rollover indices and tightly coupled template installation feature.
ES template definition should handle within ES plugin.
We don't want to handle/detect pre-installed ES template in ES plugin.

So, we recommend to handle ES template in ES plugin.

**Comment by waynetaylor** [comment] 2020-05-28 04:19
Could someone provide a working configuration with ILM. I can then test this and make changes as needed.

**Comment by cosmo0920** [comment] 2020-07-08 07:09
Maybe related to #761 ?

**Comment by cosmo0920** [comment] 2020-07-20 01:48
With logstash_format as true, ES plugin hadn't worked correctly.
I'd fixed this on v4.1.1 and working with:

```aconf
  <match test.*>
    @type elasticsearch
    @log_level "debug"
    hosts "localhost:9201"
    suppress_type_name true
    time_key "time"
    time_key_format "%Y-%m-%dT%H:%M:%S%N%z"
    logstash_format true
    logstash_prefix "fluentd"
    reconnect_on_error true
    reload_on_failure true
    reload_connections false
    request_timeout 10
    default_elasticsearch_version 7
    fail_on_detecting_es_version_retry_exceed false
    max_retry_get_es_version 2
    log_es_400_reason true
    selector_class_name "Fluent::Plugin::ElasticseatchFallbackSelector"
    reload_after 3
    with_transporter_log true
    verify_es_version_at_startup true
    template_name "logstash-default"
    template_file "index_template.json"
    ilm_policy_id "retention-policy"
    ilm_policy {"policy":{"phases":{"hot":{"min_age":"0ms","actions":{"rollover":{"max_age":"1d","max_size":"5gb"}}},"delete":{"min_age":"2d","actions":{"delete":{}}}}}}
    ilm_policy_overwrite false
    enable_ilm true
    <buffer tag>
      @type "memory"
      flush_interval 1s
      retry_type exponential_backoff
      retry_max_times 17
      chunk_limit_size 32MB
      total_limit_size 12288MB
      disable_chunk_backup true
    </buffer>
  </match>
```

```json
{
    "index_patterns": [
        "logstash-default*"
    ],
    "settings": {
        "index": {
            "number_of_replicas": "1"
        }
    }
}
```

```
$ echo '{"elmo":"3years old", "abby":"a fairy","message":"On the youtube!"}' | bundle exec fluent-cat test.json_array 
```

And then, logstash formatted indices are managed with ILM:

```bash
$  curl localhost:9201/{fluentd-2020.07.20,fluentd-default-2020.07.20-000001}/_ilm/explain | jq . 
```

```json
{
  "indices": {
    "fluentd-default-2020.07.20-000001": {
      "index": "fluentd-default-2020.07.20-000001",
      "managed": true,
      "policy": "retention-policy",
      "lifecycle_date_millis": 1595206362970,
      "age": "54.29m",
      "phase": "hot",
      "phase_time_millis": 1595206363158,
      "action": "rollover",
      "action_time_millis": 1595206448276,
      "step": "check-rollover-ready",
      "step_time_millis": 1595206448276,
      "phase_execution": {
        "policy": "retention-policy",
        "phase_definition": {
          "min_age": "0ms",
          "actions": {
            "rollover": {
              "max_size": "5gb",
              "max_age": "1d"
            }
          }
        },
        "version": 1,
        "modified_date_in_millis": 1595087792559
      }
    }
  }
}
{
  "indices": {
    "fluentd-default-2020.07.20-000001": {
      "index": "fluentd-default-2020.07.20-000001",
      "managed": true,
      "policy": "retention-policy",
      "lifecycle_date_millis": 1595206362970,
      "age": "54.29m",
      "phase": "hot",
      "phase_time_millis": 1595206363158,
      "action": "rollover",
      "action_time_millis": 1595206448276,
      "step": "check-rollover-ready",
      "step_time_millis": 1595206448276,
      "phase_execution": {
        "policy": "retention-policy",
        "phase_definition": {
          "min_age": "0ms",
          "actions": {
            "rollover": {
              "max_size": "5gb",
              "max_age": "1d"
            }
          }
        },
        "version": 1,
        "modified_date_in_millis": 1595087792559
      }
    }
  }
}
```

**Comment by cosmo0920** [comment] 2020-07-20 01:49
@waynetaylor Sorry for being late. The above comment is answered your request?

**Comment by waynetaylor** [comment] 2020-07-22 21:16
@cosmo0920  - currently testing and validating this change

**Comment by waynetaylor** [comment] 2020-07-22 21:55
![Screen Shot 2020-07-22 at 4 52 49 PM](https://user-images.githubusercontent.com/2912112/88232726-fb54d900-cc3b-11ea-961b-8d8163a5e479.png)

@cosmo0920  - after upgrade to the latest version and on 7.6.2 I was able to get this to work. I was also enable to verify changes to ILM policy reflected

**Comment by cosmo0920** [comment] 2020-07-22 23:26
Awesome! Thanks for confirming ILM working.
Can we close this issue?

**Closed** 2020-07-22 23:29 UTC

**Comment by cosmo0920** [comment] 2020-07-23 00:31
🎉

**Comment by maxisam** [comment] 2021-04-09 20:51
@cosmo0920 

Thank you for you example. However, I am still have some questions.

Is it necessary to have this part 

```yml
    template_name "logstash-default"
    template_file "index_template.json"
    ilm_policy_id "retention-policy"
    ilm_policy {"policy":{"phases":{"hot":{"min_age":"0ms","actions":{"rollover":{"max_age":"1d","max_size":"5gb"}}},"delete":{"min_age":"2d","actions":{"delete":{}}}}}}
    ilm_policy_overwrite false
    enable_ilm true
```

in the fluentd config? I thought I can use index template defined in the elasticsearch and it will grab every index with the matching pattern.
And I just need to link ilm with index template?

**Comment by cosmo0920** [comment] 2021-04-10 10:04
>　 I thought I can use index template defined in the elasticsearch and it will grab every index with the matching pattern.
And I just need to link ilm with index template?

Yes. They are needed.
I prefer to specify ILM parameters explicitly instead of using default values.

**Comment by maxisam** [comment] 2021-04-11 18:03
> > I thought I can use index template defined in the elasticsearch and it will grab every index with the matching pattern.
> > And I just need to link ilm with index template?
> 
> Yes. They are needed.
> I prefer to specify ILM parameters explicitly instead of using default values.

Thanks for the quick response. I am still a bit confused. So what is the point to have the index pattern defined in index template?
I didn't assign ILM or index template from fluentd config and it seems like working fine. Just not the rollover part.

**Comment by cosmo0920** [comment] 2021-04-12 02:55
> So what is the point to have the index pattern defined in index template?
> I didn't assign ILM or index template from fluentd config and it seems like working fine. Just not the rollover part.

They are automatically defined in runtime:
https://github.com/uken/fluent-plugin-elasticsearch/blob/master/lib/fluent/plugin/elasticsearch_index_template.rb#L134-L160

Some ILM settings defined and fixed at runtime.
We implemented them to work well at runtime.

**Comment by maxisam** [comment] 2021-04-12 04:46
@cosmo0920 I see. So it more like a choice. Thx

**Comment by rshiva777** [comment] 2022-10-14 03:26
Hello @cosmo0920, 

Need your support on the below issues. Could you please check and update.

https://github.com/uken/fluent-plugin-elasticsearch/issues/752#issuecomment-660754130
As per the above comments, index rollover is working as expected. But i see 2 issues here.

1.  The index template creating by fluentd is "Legacy index template" which is showing as deprecated in elastic v7.17.3 version. How can we move this to composable index template

![image](https://user-images.githubusercontent.com/42074614/195754927-de4014d9-5881-4c63-9d5f-6cb87bfe3258.png)

2. The logs rollover is getting happend, but the issue is,

efk_bilogs-default-2022.10.12-000001
efk_bilogs-default-2022.10.12-000002
efk_bilogs-default-2022.10.12-000003  # Yesterday indices are still getting rollover continuously even after the day has 
                                                                  completed and  new indice with efk_bilogs-default-**2022.10.13**.00001 is created
efk_bilogs-default-2022.10.13-000001
efk_bilogs-default-2022.10.13-000002


Can you please help on the above 2 issues.
