### ISSUE TITLE
mapper_parsing_exception: object mapping tried to parse field as object but found a concrete value"

### ISSUE THREAD

**Issue by GAHila** [uken/fluent-plugin-elasticsearch#581] opened 2019-04-23 14:09 UTC
#### Problem

`dump an error event: error_class=Fluent::Plugin::ElasticsearchErrorHandler::ElasticsearchError error="400 - Rejected by Elasticsearch [error type]: mapper_parsing_exception [reason]: 'object mapping for [responseObject.status] tried to parse field [status] as object, but found a concrete value'"
`

We use k8s.gcr.io/fluentd-elasticsearch:v2.4.0 to retrieve EKS audit logs.

However it seems that reponseObject sometimes comes as a json object and sometimes comes as a string.

It appears that when we receive EKS audit logs most of the logs have responseObject a json object:

```
"responseObject":{  
   "kind":"SubjectAccessReview",
   "apiVersion":"authorization.k8s.io/v1beta1",
   "metadata":{  
      "creationTimestamp":null
   },
   "spec":{  
      "nonResourceAttributes":{  
         "path":"/",
         "verb":"get"
      },
      "user":"system:anonymous",
      "group":[  
         "system:unauthenticated"
      ]
   },
   "status":{  
      "allowed":true,
      "reason":"RBAC: allowed by ClusterRoleBinding \"cluster-system-anonymous\" of ClusterRole \"cluster-admin\" to User \"system:anonymous\""
   }
},
```

but sometimes we get  status as just a string

`"status":"Success"`

which apparently ES is expecting it to be a json object.

#### Expected Behavior or What you need to ask

Is there any way to rectify this?

#### Using Fluentd and ES plugin versions

* OS version
   EC2 Amazon linux
* Bare Metal or within Docker or Kubernetes or others?
     EKS  (kubernetes 1.11)
* Fluentd v0.12 or v0.14/v1.0
     fluentd 1.3.3
* ES plugin 3.x.y/2.x.y or 1.x.y
     'fluent-plugin-elasticsearch' version '3.0.2'

    'fluent-plugin-cloudwatch-logs' version '0.7.3'
    'fluent-plugin-concat' version '2.3.0'
    'fluent-plugin-detect-exceptions' version '0.0.11'
    'fluent-plugin-kubernetes_metadata_filter' version '2.1.6'
    'fluent-plugin-multi-format-parser' version '1.0.0'
    'fluent-plugin-prometheus' version '1.3.0'
    'fluent-plugin-rewrite-tag-filter' version '2.2.0'
    'fluent-plugin-systemd' version '1.0.1'
    'fluentd' version '1.3.3'
     
* ES version (optional)
  
"version" : {
    "number" : "6.3.2",
    "build_flavor" : "oss",
    "build_type" : "tar",
    "build_hash" : "053779d",
    "build_date" : "2018-07-20T05:20:23.451332Z",
    "build_snapshot" : false,
    "lucene_version" : "7.3.1",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },

**Comment by cosmo0920** [comment] 2019-05-13 07:10
Similar to https://github.com/uken/fluent-plugin-elasticsearch/issues/452?

**Comment by cosmo0920** [comment] 2019-07-30 08:50
Dupe of #452. Closing.

**Closed by cosmo0920** 2019-07-30 08:50 UTC
