### ISSUE TITLE
Timezone problem

### ISSUE THREAD

**Issue by chenjienn** [uken/fluent-plugin-elasticsearch#534] opened 2019-01-28 10:29 UTC
#### Problem

When the timestamp field in my log is  00:00:00 ,  the field in es is  08:00:00.  My timezone is +8:00 , how  can i  store the correct timestamp  

the  attach file is the fluentd config file.

#### Using Fluentd and ES plugin versions
* td-agent 3.2.1
  * paste result of ``fluentd --version`` or ``td-agent --version``
* ES version 6.2.3
[td-agent.conf.dest.txt](https://github.com/uken/fluent-plugin-elasticsearch/files/2802479/td-agent.conf.dest.txt)
[td-agent.conf.source.txt](https://github.com/uken/fluent-plugin-elasticsearch/files/2802480/td-agent.conf.source.txt)

**Comment by cosmo0920** [comment] 2019-01-29 01:52
Could you try `timekey_use_utc` and `timekey_zone`:

```aconf
<match test.json>
  @type elasticsearch
#  with_transporter_log true
  verify_es_version_at_startup false
  default_elasticsearch_version 6
  hosts 10.23.33.35:19200,10.23.33.36:19200
  scheme http
  ssl_verify false
  index_name fluentd.test-%Y.%m.%d
  type_name fluentd
  <buffer tag,time>
    @type memory
    timekey 3600
    # Assume UTC or other time zone. Adjust for your usage.
    timekey_use_utc true
    timekey_zone +0000
  </buffer>
#  logstash_format true
#  logstash_prefix fluentd.test-%Y.%m.%d
</match>
```

ref: https://docs.fluentd.org/v1.0/articles/buffer-section#argument

**Comment by chenjienn** [comment] 2019-01-29 02:09
it is not uesful
by the way,  my log is a json file and the timestamp in log is just liket this: [{"@timestamp":"2019-01-14T16:00:01.483+00:00"}] , 
![kibana](https://user-images.githubusercontent.com/13412289/51879337-f51acf00-23ad-11e9-88e1-d1af16240977.png)

**Comment by cosmo0920** [comment] 2019-01-29 02:14
> it is not uesful

`timekey_use_utc` and `timekey_zone` have no effect in your environment, right?

**Comment by chenjienn** [comment] 2019-01-29 02:19
> > it is not uesful
> 
> `timekey_use_utc` and `timekey_zone` have no effect in your environment, right?
yes,  i  set  timekey_use_utc to true and change timekey_zone to different value , but have no effect

**Comment by cosmo0920** [comment] 2019-01-29 03:06
Could you provide your json log sample without sensitive information?
I guess that timezone part is wrongly parsed or ignored.

**Comment by chenjienn** [comment] 2019-01-29 03:46
{"@timestamp":"2019-01-14T16:00:01.483+00:00","severity":"INFO","service":"spn","trace":"f8cb9cd40c6a4f4b","span":"f8cb9cd40c6a4f4b","exportable":"false","pid":"34492","thread":"http-nio-8666-exec-264",..........(many other key-value field) }

**Comment by cosmo0920** [comment] 2019-01-29 05:39
`parse_json` can handle timekey in JSON with `time_key`.
And using `include_timestamp` paramater on ES plugin, we can handle timestamp in JSON as localtime and adding `@timestamp` at the same time:

### Source

```aconf
﻿﻿<source>
  @type tail
  path /path/to/your/log/*.json
  read_from_head true
  tag test.json
  <parse>
    @type json
    time_key @timestamp
    # Matches YYYY-mm-ddTHH:MM:SS.N{1,9}(+|-)ZZ:ZZ
    time_format %Y-%m-%dT%H:%M:%S.%N%z 
  </parse>
</source>
```

### Destination

```aconf
<match test.json>
  @type elasticsearch
#  with_transporter_log true
  verify_es_version_at_startup false
  default_elasticsearch_version 6
  hosts YOUR_ES_HOSTS
  scheme http
  ssl_verify false
  index_name fluentd.test-%Y.%m.%d
  type_name fluentd
  include_timestamp
  <buffer tag,time>
    @type memory
    timekey 3600
    timekey_zone Asia/Tokyo # or Asia/Beijing and so on.
  </buffer>
#  logstash_format true
#  logstash_prefix fluentd.test-%Y.%m.%d
</match>
```

**Comment by chenjienn** [comment] 2019-01-29 08:52
it doesn't work …… but the indices seems already change
![kibana](https://user-images.githubusercontent.com/13412289/51895835-11d2f900-23e6-11e9-9d39-fea5d74b3a72.png)
the index was 2019.01.14 but the @timestamp field was 2019.01.15

**Comment by cosmo0920** [comment] 2019-01-30 02:09
How about this?

### Source 

```aconf
<source>
  @type tail
  path ./*.json
  read_from_head true
  tag test.json
  <parse>
    @type json
    time_key @timestamp
    time_format %Y-%m-%dT%H:%M:%S.%N%z
    # Preserve `@timestamp` key in events
    keep_time_key true
  </parse>
</source>
```

### Destination

```aconf
<match test.json>
  @type elasticsearch
#  with_transporter_log true
  verify_es_version_at_startup false
  default_elasticsearch_version 6
  hosts localhost
  scheme http
  ssl_verify false
  index_name fluentd.test-%Y.%m.%d
  type_name fluentd
  include_timestamp
  <buffer tag,time>
    @type memory
    timekey 3600
  </buffer>
#  logstash_format true
#  logstash_prefix fluentd.test-%Y.%m.%d
</match>
```

I got the following result:

```json
      {
        "_index" : "fluentd.test-2019.01.14",
        "_type" : "fluentd",
        "_id" : "HjuAnGgBV2UnL8Kuw1u-",
        "_score" : 1.0,
        "_source" : {
          "@timestamp" : "2019-01-14T16:00:01.483+00:00",
          "severity" : "INFO",
          "service" : "spn",
          "trace" : "f8cb9cd40c6a4f4b",
          "span" : "f8cb9cd40c6a4f4b",
          "exportable" : "false",
          "pid" : "34492",
          "thread" : "http-nio-8666-exec-264"
        }
      }
```

**Comment by chenjienn** [comment] 2019-01-30 03:39
this time the timestamp in es is correct,  but the problem is "@timestamp" : "2019-01-14T16:00:01.483+00:00"  which timezone is +00:00 so when i search this record in kibana, the timestamp is alse the 00:00:01.483 , is there a way to rewrite the timezone correct?

**Comment by chenjienn** [comment] 2019-01-30 14:11
ok,  i think use UTC in es is correct, thanks a lot

**Comment by cosmo0920** [comment] 2019-01-30 14:17
Thank you for cooperative investigation.
It is very helpful for us.
Can we close this issue?

**Comment by chenjienn** [comment] 2019-01-30 14:24
> Thank you for cooperative investigation.
> It is very helpful for us.
> Can we close this issue?

sure

**Closed** 2019-01-31 00:42 UTC

**Comment by chenjienn** [comment] 2019-02-10 06:10
Hi~ i have another problem ,  when i use the configuration you suggested above, the log will take a few minutes to be able to search in es after reading it from json file.

**Comment by cosmo0920** [comment] 2019-02-12 04:35
Because ES plugin is buffered output plugin.
flush_inerval is specified as 60s by default: https://docs.fluentd.org/v1.0/articles/buffer-section#flushing-parameters

I'm personally not recommended to make more short flush interval.
It causes high CPU load in ES cluster.

**Comment by chenjienn** [comment] 2019-02-12 06:52
thanks a lot for your patience to explain !

**Comment by cosmo0920** [comment] 2019-02-12 07:05
No worries. I'd love to support Fluentd users.
Please feel free to send any questions about ES plugin into this repository. :smile:

**Comment by aymenwerg** [comment] 2020-07-23 14:59
Hii Guys, I got this error when i try to deploy fluentd on my K8s cluster :
[warn]: #0 [out_es] Could not connect Elasticsearch or obtain version. Assuming Elasticsearch 5.
And when i add **verify_es_version_at_startup false**  in my configmap.yml nothing changed.
Any help please !

`2020-07-23 14:54:36 +0000 [info]: #0 [in_tail_container_logs] following tail of /var/log/containers/php-horizon-f95766fc8-jtc7t_opsdashboard_php-horizon-fdc1792258f9d0dc7584a3ea40b78cf988cebc69649e53333117e61087222daf.log
2020-07-23 14:54:37 +0000 [info]: Worker 0 finished unexpectedly with signal SIGKILL
2020-07-23 14:54:37 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '2.11.11'
2020-07-23 14:54:37 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '2.1.4'
2020-07-23 14:54:37 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.1.0'
2020-07-23 14:54:37 +0000 [info]: gem 'fluent-plugin-systemd' version '1.0.1'
2020-07-23 14:54:37 +0000 [info]: gem 'fluentd' version '1.3.0'
2020-07-23 14:54:37 +0000 [info]: adding match pattern="fluent.**" type="null"
2020-07-23 14:54:37 +0000 [info]: adding filter pattern="kubernetes.**" type="kubernetes_metadata"
2020-07-23 14:54:38 +0000 [info]: adding match pattern="**" type="elasticsearch"
2020-07-23 14:54:38 +0000 [warn]: #0 [out_es] Could not connect Elasticsearch or obtain version. Assuming Elasticsearch 5.
2020-07-23 14:54:38 +0000 [info]: adding source type="systemd"
2020-07-23 14:54:38 +0000 [info]: adding source type="systemd"
2020-07-23 14:54:38 +0000 [info]: adding source type="systemd"
2020-07-23 14:54:38 +0000 [info]: adding source type="tail"
2020-07-23 14:54:38 +0000 [info]: adding source type="tail"
2020-07-23 14:54:38 +0000 [info]: adding source type="tail"
2020-07-23 14:54:38 +0000 [info]: adding source type="tail"
2020-07-23 14:54:38 +0000 [info]: adding source type="tail"
2020-07-23 14:54:38 +0000 [info]: adding source type="tail"
2020-07-23 14:54:38 +0000 [info]: adding source type="tail"
2020-07-23 14:54:38 +0000 [info]: adding source type="tail"
2020-07-23 14:54:38 +0000 [info]: adding source type="tail"
2020-07-23 14:54:38 +0000 [info]: adding source type="tail"
2020-07-23 14:54:38 +0000 [info]: adding source type="tail"
2020-07-23 14:54:38 +0000 [info]: adding source type="tail"
2020-07-23 14:54:38 +0000 [info]: adding source type="tail"
2020-07-23 14:54:38 +0000 [info]: adding source type="tail"
2020-07-23 14:54:38 +0000 [info]: #0 starting fluentd worker pid=488 ppid=6 worker=0
2020-07-23 14:54:39 +0000 [info]: Worker 0 finished unexpectedly with signal SIGKILL
2020-07-23 14:54:39 +0000 [info]: gem 'fluent-plugin-elasticsearch' version '2.11.11'
2020-07-23 14:54:39 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '2.1.4'
2020-07-23 14:54:39 +0000 [info]: gem 'fluent-plugin-rewrite-tag-filter' version '2.1.0'`

**Comment by cosmo0920** [comment] 2020-07-24 02:43
We mainly didn't suppport imcomplete k8s issue report.
Could you send your issue into Fluentd mailing list?
Notebook that you should send your issue with:
* using fluentd daemonset version and configMap if you are using
* using Elasticsearch helm chart version or Elasticsearch cluster deploying way if you are using
* other yaml configuration for k8s or executed kubectl command logs for reproducible report

Thanks for using Elasticsearch plugin.
