### ISSUE TITLE
Indices get created in past, present and future

### ISSUE THREAD

**Issue by davideagle** [uken/fluent-plugin-elasticsearch#647] opened 2019-10-11 01:01 UTC
(check apply)
- [x] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

#### Problem
I'm deploying fluentd-elasticsearch chart from chart from https://github.com/kiwigrid/helm-charts/tree/master/charts/fluentd-elasticsearch and Indices get created with wrong date. Over the course of 2 minutes the following indices are created

x-logstash-2064.03.27
x-logstash-2064.03.26
x-logstash-2064.03.25
x-logstash-2064.03.08
x-logstash-2019.10.09
x-logstash-1970.01.01

*x-logstash-2064.04.22 log entry and index entry*
https://gist.github.com/davideagle/b7ebb541d084b0494f2fd737c63fe95c

*x-logstash-1970.01.01  log entry and index entry*
https://gist.github.com/davideagle/9f945dc555b549541ce5a5afa57b3ea4
all entries are with the same timestamp 1970-01-01T00:33:39.000Z 

#### Steps to replicate

*Chart Values*
https://gist.github.com/davideagle/dd2844807df904331f23bec045697451

*output.conf*
```
      <match **>
        @id xlogstash
        @type elasticsearch
        @log_level "#{ENV['OUTPUT_LOG_LEVEL']}"
        include_tag_key true
        host "#{ENV['OUTPUT_HOST']}"
        port "#{ENV['OUTPUT_PORT']}"
        path "#{ENV['OUTPUT_PATH']}"
        scheme "#{ENV['OUTPUT_SCHEME']}"
        ssl_verify "#{ENV['OUTPUT_SSL_VERIFY']}"
        ssl_version "#{ENV['OUTPUT_SSL_VERSION']}"
        logstash_format true
        logstash_prefix "x-logstash"
        type_name _doc
        reconnect_on_error true
        <buffer>
          @type file
          path /var/log/fluentd-buffers/kubernetes.xlogstash.buffer
          flush_mode interval
          retry_type exponential_backoff
          flush_thread_count 2
          flush_interval 5s
          retry_forever
          retry_max_interval 30
          chunk_limit_size "#{ENV['OUTPUT_BUFFER_CHUNK_LIMIT']}"
          queue_limit_length "#{ENV['OUTPUT_BUFFER_QUEUE_LIMIT']}"
          overflow_action block
        </buffer>
      </match>
```
#### Expected Behavior or What you need to ask
Logs should be shipped to the right index based on timestamp in logs
...

#### Using Fluentd and ES plugin versions

* OS version
* Kubernetes v1.11.7
* Fluentd v1.6.3
* ES plugin 3.5.4

´´´
activesupport (5.2.3)
addressable (2.6.0)
bigdecimal (1.2.8)
concurrent-ruby (1.1.5)
cool.io (1.5.4)
did_you_mean (1.0.0)
dig_rb (1.0.1)
domain_name (0.5.20190701)
elasticsearch (7.3.0)
elasticsearch-api (7.3.0)
elasticsearch-transport (7.3.0)
excon (0.65.0)
faraday (0.15.4)
ffi (1.11.1)
fluent-plugin-concat (2.4.0)
fluent-plugin-detect-exceptions (0.0.12)
fluent-plugin-elasticsearch (3.5.4)
fluent-plugin-kubernetes_metadata_filter (2.2.0)
fluent-plugin-multi-format-parser (1.0.0)
fluent-plugin-prometheus (1.4.0)
fluent-plugin-systemd (1.0.2)
fluentd (1.6.3)
http (0.9.8)
http-cookie (1.0.3)
http-form_data (1.0.3)
http_parser.rb (0.6.0)
i18n (1.6.0)
io-console (0.4.5)
json (1.8.3)
kubeclient (1.1.4)
lru_redux (1.1.0)
mime-types (3.2.2)
mime-types-data (3.2019.0331)
minitest (5.11.3, 5.9.0)
msgpack (1.3.0)
multi_json (1.13.1)
multipart-post (2.1.1)
net-telnet (0.1.1)
netrc (0.11.0)
oj (3.8.1)
power_assert (0.2.7)
prometheus-client (0.9.0)
psych (2.1.0)
public_suffix (3.1.1)
quantile (0.2.1)
rake (10.5.0)
rdoc (4.2.1)
recursive-open-struct (1.0.0)
rest-client (2.0.2)
serverengine (2.1.1)
sigdump (0.2.4)
strptime (0.2.3)
systemd-journal (1.3.3)
test-unit (3.1.7)
thread_safe (0.3.6)
tzinfo (1.2.5)
tzinfo-data (1.2019.2)
unf (0.1.4)
unf_ext (0.0.7.6)
yajl-ruby (1.4.1)
´´´
* ES version 6.7

**Comment by GrantSheehan** [comment] 2019-10-15 17:43
I'm seeing similar behavior. The common thread on my misplaced logs seems to be javascript. I'm still digging.

**Comment by davideagle** [comment] 2019-10-16 15:53
I identified a pod logging with unix time and as soon as I removed it is stopped getting indices created in the future 

´´´
{
  "level": 30,
  "time": 1571240380634,
  "pid": 17,
  "hostname": "kubernetes-external-secrets-5fc8d8b587-gmq8v",
  "msg": "upserting secret docker-registry-pull-secret in sandbox",
  "v": 1
}
´´´

**Comment by labosen** [comment] 2019-11-21 06:49
it seems that field 'time' in json-string cause this time-travel problem;

**change the json field 'time'  to 'xxtime' to avoid this problem;**

guess maybe the popular word 'time' may cause extra function in fluentd(Ruby, C) , ES(Java), or Kibana (JavaScript&JavaScript), makes the time-travel problem.

**Comment by GrantSheehan** [comment] 2019-11-21 17:30
I've swapped to using the [fluent-bit helm chart](https://github.com/helm/charts/tree/master/stable/fluent-bit) for kubernetes logging instead and I've been having better luck with it.

**Comment by cosmo0920** [comment] 2019-11-22 03:00
This issue seems to be caused by sourcing section:
https://github.com/kiwigrid/helm-charts/blob/master/charts/fluentd-elasticsearch/templates/configmaps.yaml#L127-L135

Your configuration works not to handle time_key as time record.
So, I guess wrong time is transferred source section.

Could you confirm that parsing time format for logfile is whether correct or not.

**Comment by labosen** [comment] 2019-11-22 05:57
origin is json type log in a .txt file, and contents like below in each line:
    

mainly use for data analysis,
this 'time' is a little different from 'timestamp',(not the same occur time)
the log in elasticsearch is return to 1970-01-01,
    (index_name: fruit-shop19700101)
and the log in elasticsearch is:
    @timestamp: January 1st 1970, 08:33:39.000

===================================
i change the log into:
{'fieldA': 123, 'fieldB': 456, 'fieldC':789, 'sptime': '2019-11-18 09:30:00'}

everything work fine.
So this is why i say avaid using field 'time' in origin log content.

----------------------------------------------------------
config like below:
<source>
  @type tail
  path C:\log_d\data01.txt
  pos_file C:\log_d\place01.pos
  tag pikachu
  read_from_head true
  <parse>
      @type json
      keep_time_key true
  </parse>	
</source>
<match pikachu.**>
  @type elasticsearch
  host 127.0.0.1
  port 9200
  logstash_format true
  logstash_prefix fruit-shop
  include_timestamp true  # this generate the timestamp
  <buffer tag, time>  
	timekey 5s  
	timekey_wait 1s  
  </buffer>  
</match>

**Comment by cosmo0920** [comment] 2019-12-10 08:34
> _x-logstash-1970.01.01 log entry and index entry_
> https://gist.github.com/davideagle/9f945dc555b549541ce5a5afa57b3ea4
> all entries are with the same timestamp 1970-01-01T00:33:39.000Z

This time records is interpreted as null (0).
This is because timestamp format glitch.

And

> x-logstash-2064.04.22 log entry and index entry
https://gist.github.com/davideagle/b7ebb541d084b0494f2fd737c63fe95c

This time records is interpreted as overshooted future time.
This is because this timestamp format is millisecond unit unixepoch not second unit unixepoch.

To prevent this timestamp glitch, users should specify timestamp format in in_tail configuration.

**Comment by cosmo0920** [comment] 2020-07-07 06:09
This issue is caused by timestamp format glitch on tail plugin:
https://github.com/kiwigrid/helm-charts/blob/master/charts/fluentd-elasticsearch/templates/configmaps.yaml#L120-L139

This is not ES plugin issue. So closed.

**Closed by cosmo0920** 2020-07-07 06:09 UTC
Labels: kubernetes
