### ISSUE TITLE
Sending logs silently dies

### ISSUE THREAD

**Issue by Fodoj** [uken/fluent-plugin-elasticsearch#66] opened 2014-08-19 17:19 UTC
I have following configuration:

```
<match apache.**>
  type elasticsearch
  logstash_format true
  host my-es-host.com
  port 80
  index_name fluentd
  type_name fluentd
  logstash_prefix apache
  buffer_chunk_limit 10m
  buffer_queue_limit 64
  flush_interval 5s
</match>
```

For some reason sometimes it just stops sending any apache logs to my ES cluster, without any errors or anything. After I restart fluentd it works fine again, but I expect now it to fail again.

Is there any way to debug such situations? Any proposals why it happens at all?

**Comment by ianseyer** [comment] 2017-06-28 19:29
@Fodoj what was the tiny fix?

I am now getting this error almost exactly - initially i had to change `localhost` to `127.0.0.1`, and it worked for 11 records and then stopped silently. Nothing in the logs indicates any sort of failure whatsoever, but even restarting `td-agent` does not fix things.

This is my conf:

```
<match debug.**>
  type stdout
</match>

<source>
  type forward
</source>

<source>
  type http
  port 8888
</source>

## live debugging agent
<source>
  type debug_agent
  bind 127.0.0.1
  port 24230
</source>

#
# SYSLOG
#
# get logs from syslog
<source>
  @type syslog
  port 42185
  tag syslog
</source>

<match **>
  @type elasticsearch
  host 127.0.0.1
  port 9200
  logstash_format true
  index_name kibana
  flush_interval 10s # for testing

  # buffering
  buffer_type memory
  buffer_chunk_limit 16m
  buffer_queue_limit 4096
  retry_wait 15s
</match>
```

**Comment by Fodoj** [comment] 2017-06-28 19:33
Wish I could help! It's been 3 years so I have no idea now.

**Comment by cosmo0920** [comment] 2017-12-20 05:22
@ianseyer Could you try to reproduce your issue with `with_transporter_log true` on v1.13.1 or v2.4.1?
They will output transport layer log into plugin logging mechanism.

**Comment by cosmo0920** [comment] 2018-01-16 09:24
This issue seems to be caused by disappearing elasticsearch-ruby-transport's layer logs.
When using `with_transporter_log true`, we can obtain them.
I'm closing this issue.
If you hit same issue, please re-open this issue.

**Closed by cosmo0920** 2018-01-16 09:24 UTC
