### ISSUE TITLE
[warn]: Could not push logs to Elasticsearch, resetting connection and trying again. connect_write timeout reached

### ISSUE THREAD

**Issue by johnzheng1975** [uken/fluent-plugin-elasticsearch#582] opened 2019-04-29 03:35 UTC
#### Many warning raise in fluentd log
```
2019-04-29 00:23:33 +0000 [warn]: buffer flush took longer time than slow_flush_log_threshold: elapsed_time=31.253766102716327 slow_flush_log_threshold=20.0 plugin_id="object:3fb36e8d4058"
2019-04-29 00:23:33 +0000 [warn]: buffer flush took longer time than slow_flush_log_threshold: elapsed_time=31.261768959928304 slow_flush_log_threshold=20.0 plugin_id="object:3fb36e8d4058"
2019-04-29 00:23:33 +0000 [warn]: buffer flush took longer time than slow_flush_log_threshold: elapsed_time=30.733624476008117 slow_flush_log_threshold=20.0 plugin_id="object:3fb36e8d4058"
2019-04-29 01:39:18 +0000 [warn]: Could not push logs to Elasticsearch, resetting connection and trying again. connect_write timeout reached
2019-04-29 01:39:18 +0000 [warn]: Could not push logs to Elasticsearch, resetting connection and trying again. connect_write timeout reached
```

#### Steps to replicate
*  Install search guard git@github.com:floragunncom/search-guard-helm.git
*  elastic search is 6.4.1
*  Use fluentd, with  Image:          k8s.gcr.io/fluentd-elasticsearch:v2.2.0
```
 <match kubernetes.var.log.containers.**_tryfit_**.log>
      @id elasticsearch_tryfit
      @type copy
      <store>
        @type elasticsearch
        @log_level info
        type_name fluentd
        include_tag_key true
        host 10.200.199.79
        port 30920
        scheme https
        ssl_verify false
        user admin
        password adminp
        ssl_version TLSv1_2
        logstash_format true
        logstash_prefix dev1c_tryfit
        #flush_interval 1s
        <buffer>
          @type file
          path /var/log/fluentd-buffers-tryfit-r/kubernetes.system.buffer
          flush_mode interval
          retry_type exponential_backoff
          flush_thread_count 4
          flush_interval 5s
          retry_forever
          retry_max_interval 30
          delayed_commit_timeout 90
          chunk_limit_size 2M
          queue_limit_length 64
          overflow_action block
        </buffer>
      </store>
    </match>
```

Version:
```
cat Gemfile
source 'https://rubygems.org'

gem 'fluentd', '<=1.2.4'
gem 'activesupport', '~>5.2.1'
gem 'fluent-plugin-kubernetes_metadata_filter', '~>2.0.0'
gem 'fluent-plugin-elasticsearch', '~>2.11.5'
gem 'fluent-plugin-systemd', '~>1.0.1'
gem 'fluent-plugin-detect-exceptions', '~>0.0.11'
gem 'fluent-plugin-prometheus', '~>1.0.1'
gem 'fluent-plugin-multi-format-parser', '~>1.0.0'
gem 'oj', '~>3.6.5'
```

Dockerfile
```
FROM debian:stretch-slim

ARG DEBIAN_FRONTEND=noninteractive

COPY clean-apt /usr/bin
COPY clean-install /usr/bin
COPY Gemfile /Gemfile

# 1. Install & configure dependencies.
# 2. Install fluentd via ruby.
# 3. Remove build dependencies.
# 4. Cleanup leftover caches & files.
RUN BUILD_DEPS="make gcc g++ libc6-dev ruby-dev libffi-dev" \
    && clean-install $BUILD_DEPS \
                     ca-certificates \
                     libjemalloc1 \
                     ruby \
    && echo 'gem: --no-document' >> /etc/gemrc \
    && gem install --file Gemfile \
    && apt-get purge -y --auto-remove \
                     -o APT::AutoRemove::RecommendsImportant=false \
                     $BUILD_DEPS \
    && clean-apt \
    # Ensure fluent has enough file descriptors
    && ulimit -n 65536

# Copy the Fluentd configuration file for logging Docker container logs.
COPY fluent.conf /etc/fluent/fluent.conf
COPY run.sh /run.sh

# Expose prometheus metrics.
EXPOSE 80

ENV LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.1

# Start Fluentd to pick up our config that watches Docker container logs.
CMD /run.sh $FLUENTD_ARGS
```

**Comment by cosmo0920** [comment] 2019-05-01 07:24
Try https://github.com/uken/fluent-plugin-elasticsearch#stopped-to-send-events-on-k8s-why.

**Comment by data-dude** [comment] 2019-12-17 14:56
I ran into this issue and i increased the amount of CPUs available to Elastic and that fixed the problem right away.

**Comment by cosmo0920** [comment] 2019-12-17 15:09
Thanks for the solution.

**Comment by data-dude** [comment] 2019-12-17 15:25
No problem.  I was gathering metrics for threadpool rejections and saw that spiked and Elastic was using almost all the cpu it could so I should have known it was a cpu constraint issue.

**Comment by cosmo0920** [comment] 2019-12-19 01:26
Added FAQ in #687. This is caused by exhausted Elasticsearch cluster.
Not fluent-plugin-elasticsearch issue.
Closing.

**Closed by cosmo0920** 2019-12-19 01:26 UTC
Labels: waiting-on-feedback
